from __future__ import annotations

from typing import Any


PRIMARY_COMPONENT_LIBRARY: dict[str, dict[str, Any]] = {
    "game_hud": {
        "version": "component_spec_v1",
        "component_id": "game_hud",
        "name": "游戏状态 HUD",
        "audience": "primary_school",
        "role": "game_shell",
        "runtime": "react_radix_lucide",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "显示本轮音乐任务的得分、星级、回合、剩余时间和当前音乐目标。",
        "student_actions": ["observe", "revise"],
        "music_elements": ["课堂进度", "音乐目标"],
        "required_material_entities": [],
        "teacher_controls": ["reset", "pause", "show_hint"],
        "required_elements": ["分数", "回合", "音乐目标", "状态徽章"],
        "behaviors": ["不遮挡音乐操作区", "只显示和当前音乐任务有关的信息", "投屏可读"],
        "interaction_modes": ["desktop_mouse", "projector_large_text", "keyboard_optional"],
        "empty_state": "未开始时显示本轮音乐任务和开始状态，不显示空分数。",
        "error_state": "缺少活动状态时提示教师重置或重新生成活动。",
        "fixture": {"score": 0, "round": 1, "goal": "听稳定拍后再拍节奏"},
        "called_by_template_ids": ["rhythm_echo_core", "timbre_detective_core", "listening_choice_core"],
        "open_source_dependencies": ["react", "radix", "lucide-react"],
        "quality_gates": ["not_standalone_game", "readable_on_projector", "state_visible", "reset_ready"],
        "education_notes": ["HUD 只能辅助课堂节奏，不能把音乐学习简化成抢分。"],
    },
    "round_prompt_panel": {
        "version": "component_spec_v1",
        "component_id": "round_prompt_panel",
        "name": "回合任务提示板",
        "audience": "primary_school",
        "role": "game_shell",
        "runtime": "react_radix",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "用一句短任务告诉学生本轮先听什么、做什么、怎样算完成。",
        "student_actions": ["listen", "read", "perform"],
        "music_elements": ["任务目标", "音乐要素"],
        "required_material_entities": [],
        "teacher_controls": ["reset", "show_hint", "hide_hint"],
        "required_elements": ["任务句", "听/做步骤", "完成标准"],
        "behaviors": ["低段少文字", "提示必须包含音乐动作", "可隐藏提示"],
        "interaction_modes": ["desktop_mouse", "projector_large_text", "keyboard_optional"],
        "empty_state": "未绑定任务时显示等待教师选择音乐材料。",
        "error_state": "缺少完成标准时提示补充音乐判定规则。",
        "fixture": {"prompt": "先听一遍，再拍出四、二八、四、休止。", "standard": "休止处停住"},
        "called_by_template_ids": ["rhythm_echo_core", "lyrics_rhythm_core", "theme_return_core"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["not_standalone_game", "music_task_visible", "hint_toggle_ready", "reset_ready"],
        "education_notes": ["提示要指向听、唱、奏、动或说依据，避免只写点击说明。"],
    },
    "reward_panel": {
        "version": "component_spec_v1",
        "component_id": "reward_panel",
        "name": "音乐反馈奖励面板",
        "audience": "primary_school",
        "role": "music_feedback",
        "runtime": "react_radix_lucide",
        "layers": ["performance", "creation", "music_game", "mixed"],
        "purpose": "完成后用星级、徽章和下一步练习给出形成性反馈。",
        "student_actions": ["observe", "revise", "continue"],
        "music_elements": ["反馈", "练习建议"],
        "required_material_entities": [],
        "teacher_controls": ["reset", "continue", "difficulty_down", "difficulty_up"],
        "required_elements": ["星级", "徽章", "音乐原因", "下一步练习"],
        "behaviors": ["奖励必须附音乐原因", "失败时给可改进建议", "支持继续练习"],
        "interaction_modes": ["desktop_mouse", "projector_large_text", "keyboard_optional"],
        "empty_state": "未完成时显示等待本轮结果。",
        "error_state": "缺少判定结果时提示教师确认或重新记录。",
        "fixture": {"stars": 2, "reason": "第 3 拍略晚，休止已停住。", "next": "慢速再来一次"},
        "called_by_template_ids": ["rhythm_echo_core", "composition_puzzle_core", "timbre_detective_core"],
        "open_source_dependencies": ["react", "radix", "lucide-react"],
        "quality_gates": ["not_standalone_game", "music_reason_required", "next_practice_visible", "reset_ready"],
        "education_notes": ["奖励不能只给通关动画，必须告诉学生音乐上哪里更稳定或更清楚。"],
    },
    "progress_path": {
        "version": "component_spec_v1",
        "component_id": "progress_path",
        "name": "课堂进度路径",
        "audience": "primary_school",
        "role": "game_shell",
        "runtime": "react_svg",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "把听、模仿、表现、说明、创编等课堂步骤显示为可推进路径。",
        "student_actions": ["observe", "continue"],
        "music_elements": ["学习路径", "课堂环节"],
        "required_material_entities": [],
        "teacher_controls": ["reset", "skip", "continue"],
        "required_elements": ["当前步骤", "已完成状态", "下一步"],
        "behaviors": ["步骤对应音乐学习顺序", "支持回看", "不会替代主要操作区"],
        "interaction_modes": ["desktop_mouse", "projector_large_text"],
        "empty_state": "未开始时显示第一步为先听音乐材料。",
        "error_state": "步骤缺失时回退到听、做、说三个基础步骤。",
        "fixture": {"steps": ["听", "拍", "说依据"], "current": 1},
        "called_by_template_ids": ["listening_choice_core", "phrase_loop_core", "form_treasure_core"],
        "open_source_dependencies": ["react", "svg"],
        "quality_gates": ["not_standalone_game", "learning_path_visible", "reset_ready"],
        "education_notes": ["小学音乐活动路径应体现先体验、再表现、再理解或迁移。"],
    },
    "answer_choice_grid": {
        "version": "component_spec_v1",
        "component_id": "answer_choice_grid",
        "name": "音乐选择网格",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_radix",
        "layers": ["listening", "music_game", "mixed"],
        "purpose": "用于情绪、速度、力度、音色、唱名等听后选择。",
        "student_actions": ["listen", "choose", "explain"],
        "music_elements": ["情绪", "速度", "力度", "音色", "唱名"],
        "required_material_entities": ["audio_clip"],
        "teacher_controls": ["reset", "show_answer", "hide_hint"],
        "required_elements": ["选项卡", "禁用态", "选择反馈", "依据提示"],
        "behaviors": ["必须先听后选", "选项数量可调", "选择后要求音乐依据"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text", "keyboard_optional"],
        "empty_state": "没有选项时提示补充可听辨目标或证据词。",
        "error_state": "音频未绑定时禁止选择并提示先绑定音频。",
        "fixture": {"choices": ["轻快", "安静", "庄严"], "requires_listen_first": True},
        "called_by_template_ids": ["listening_choice_core", "timbre_detective_core", "solfege_sort_core"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["not_standalone_game", "listen_before_choice", "evidence_required", "reset_ready"],
        "education_notes": ["选择网格用于表达听觉判断，不能变成看图或猜词。"],
    },
    "drag_sort_board": {
        "version": "component_spec_v1",
        "component_id": "drag_sort_board",
        "name": "拖拽排序板",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_dnd_kit",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "用于节奏顺序、曲式段落、乐器分类和创编素材排列。",
        "student_actions": ["listen", "arrange", "classify", "create", "explain"],
        "music_elements": ["节奏", "曲式", "音色", "创编"],
        "required_material_entities": ["rhythm_pattern"],
        "teacher_controls": ["reset", "show_answer", "undo"],
        "required_elements": ["素材区", "排序区", "撤回", "检查"],
        "behaviors": ["支持点击添加的无拖拽替代", "排序后可试听或复听", "总拍数或结构可检查"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text", "keyboard_optional"],
        "empty_state": "无素材时提示补充节奏、段落或乐器材料。",
        "error_state": "素材与目标格不匹配时提示教师调整材料数量。",
        "fixture": {"items": ["A", "B", "A"], "slots": 3, "mode": "form_order"},
        "called_by_template_ids": ["form_treasure_core", "rhythm_question_core", "body_percussion_core"],
        "open_source_dependencies": ["react", "dnd-kit", "radix"],
        "quality_gates": ["not_standalone_game", "student_operable", "undo_ready", "reset_ready", "music_structure_check"],
        "education_notes": ["拖拽只是操作方式，排序依据必须来自听觉、节奏时值或音乐结构。"],
    },
    "teacher_confirm_overlay": {
        "version": "component_spec_v1",
        "component_id": "teacher_confirm_overlay",
        "name": "教师确认层",
        "audience": "primary_school",
        "role": "teacher_control",
        "runtime": "react_radix_dialog",
        "layers": ["performance", "creation", "music_game", "mixed"],
        "purpose": "用于唱回、展示、合奏进入、创编说明等不能完全自动判定的活动。",
        "student_actions": ["perform", "wait", "revise"],
        "music_elements": ["演唱", "合奏", "展示", "创编"],
        "required_material_entities": [],
        "teacher_controls": ["confirm", "retry", "hint", "reset"],
        "required_elements": ["通过", "重来", "提示", "教师备注"],
        "behaviors": ["教师确认优先", "保留重来入口", "不把儿童歌唱简单机器评分"],
        "interaction_modes": ["desktop_mouse", "projector_large_text", "keyboard_optional"],
        "empty_state": "等待学生表现时显示本次观察点。",
        "error_state": "缺少观察点时提示补充评价标准。",
        "fixture": {"observe": "是否自然唱出第 2 乐句", "actions": ["通过", "重来", "提示"]},
        "called_by_template_ids": ["phrase_loop_core", "solfege_echo_core", "orff_ensemble_core"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["not_standalone_game", "teacher_confirm_ready", "retry_ready", "reset_ready"],
        "education_notes": ["小学演唱和展示类任务应保留教师专业判断，机器只做辅助记录。"],
    },
    "classroom_scoreboard": {
        "version": "component_spec_v1",
        "component_id": "classroom_scoreboard",
        "name": "班级小组计分板",
        "audience": "primary_school",
        "role": "classroom_management",
        "runtime": "react_radix",
        "layers": ["performance", "creation", "music_game", "mixed"],
        "purpose": "记录小组合作、合奏进入、展示评价和课堂奖励。",
        "student_actions": ["cooperate", "perform", "assess"],
        "music_elements": ["合作", "合奏", "评价"],
        "required_material_entities": ["classroom_group_task", "assessment_criteria"],
        "teacher_controls": ["add_point", "undo", "reset", "save"],
        "required_elements": ["小组列表", "加分", "撤回", "重置", "记录导出"],
        "behaviors": ["分数附音乐依据", "支持撤回", "避免只按速度排名"],
        "interaction_modes": ["desktop_mouse", "projector_large_text"],
        "empty_state": "无小组时提示先生成小组任务。",
        "error_state": "评价标准缺失时只显示记录，不自动排名。",
        "fixture": {"groups": ["拍手组", "手鼓组"], "criteria": ["稳定拍", "同时进入"]},
        "called_by_template_ids": ["group_relay_core", "orff_ensemble_core", "show_and_peer_feedback_core"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["not_standalone_game", "group_state_ready", "music_evidence_required", "undo_ready", "reset_ready"],
        "education_notes": ["小组计分要奖励音乐合作和表现依据，不鼓励无音乐目标的竞争。"],
    },
    "audio_player": {
        "version": "component_spec_v1",
        "component_id": "audio_player",
        "name": "课堂播放器",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_html_audio_webaudio",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "让学生先听音乐材料，再进入拍、唱、动、选或创编。",
        "student_actions": ["listen", "replay"],
        "music_elements": ["音频", "速度", "乐句"],
        "required_material_entities": ["audio_clip"],
        "teacher_controls": ["play", "pause", "replay", "tempo", "reset"],
        "required_elements": ["播放", "暂停", "重播", "进度提示"],
        "behaviors": ["避免重复播放冲突", "播放状态清晰", "支持课堂重播"],
        "open_source_dependencies": ["react", "webaudio"],
        "quality_gates": ["audio_playable", "replay_ready", "teacher_reset_ready"],
        "education_notes": ["小学音乐活动必须先听到材料，播放器是听觉入口，不是装饰控件。"],
    },
    "compare_player": {
        "version": "component_spec_v1",
        "component_id": "compare_player",
        "name": "对比聆听播放器",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_html_audio_webaudio",
        "layers": ["listening", "music_game", "mixed"],
        "purpose": "支持学生对比不同音色、情绪、段落或版本，并说出听觉依据。",
        "student_actions": ["listen", "compare", "explain"],
        "music_elements": ["音色", "情绪", "速度", "力度"],
        "required_material_entities": ["audio_clip"],
        "teacher_controls": ["replay", "switch_audio", "reset"],
        "required_elements": ["A/B 播放", "复听", "当前音频标识"],
        "behaviors": ["切换音频不重叠", "必须先听再选", "支持复听"],
        "open_source_dependencies": ["react", "webaudio"],
        "quality_gates": ["audio_playable", "listen_before_choice", "relisten_ready"],
        "education_notes": ["欣赏和音色活动中，图片只能辅助，判断必须从听觉证据开始。"],
    },
    "rhythm_card_bank": {
        "version": "component_spec_v1",
        "component_id": "rhythm_card_bank",
        "name": "节奏卡仓库",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_pointer",
        "layers": ["performance", "creation", "music_game", "mixed"],
        "purpose": "把节奏型变成可听、可拖、可排序的课堂材料。",
        "student_actions": ["listen", "tap", "arrange", "create"],
        "music_elements": ["节奏", "节拍", "休止"],
        "required_material_entities": ["rhythm_pattern"],
        "teacher_controls": ["shuffle", "show_answer", "hide_hint", "reset"],
        "required_elements": ["节奏卡", "试听", "拖拽或点击", "时值提示"],
        "behaviors": ["节奏总拍数可校验", "休止需要明确反馈", "低段可用图形提示"],
        "open_source_dependencies": ["react", "pointer_events"],
        "quality_gates": ["material_bound", "rhythm_value_check", "student_operable"],
        "education_notes": ["节奏卡服务听、拍、读和创编，不能只作为普通拖拽拼图。"],
    },
    "solfege_card_bank": {
        "version": "component_spec_v1",
        "component_id": "solfege_card_bank",
        "name": "唱名卡仓库",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_webaudio",
        "layers": ["performance", "creation", "music_game", "mixed"],
        "purpose": "支持 do/re/mi/sol/la 等首调唱名的听辨、排序和演唱提示。",
        "student_actions": ["listen", "arrange", "sing"],
        "music_elements": ["唱名", "音高", "旋律"],
        "required_material_entities": ["solfege_set"],
        "teacher_controls": ["show_solfege", "hide_solfege", "limit_pitch_count", "reset"],
        "required_elements": ["唱名卡", "音高试听", "排序区"],
        "behaviors": ["限制音级数量", "默认使用小学首调唱名", "支持听后再排"],
        "open_source_dependencies": ["react", "webaudio"],
        "quality_gates": ["pitch_set_limited", "audio_playable", "student_operable"],
        "education_notes": ["小学音高活动要从听辨和模唱出发，不能只做符号排序。"],
    },
    "score_following_board": {
        "version": "component_spec_v1",
        "component_id": "score_following_board",
        "name": "简谱跟读板",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg_webaudio",
        "layers": ["performance", "mixed"],
        "purpose": "把简谱数字、唱名、节奏和听觉材料放在同一个跟读流程里。",
        "student_actions": ["listen", "read", "sing", "explain"],
        "music_elements": ["识谱", "唱名", "节奏", "旋律"],
        "required_material_entities": ["numbered_score", "rhythm_pattern", "audio_clip"],
        "teacher_controls": ["replay", "show_solfege", "hide_solfege", "tempo", "reset"],
        "required_elements": ["简谱行", "唱名映射", "节奏卡", "当前行高亮", "先听按钮"],
        "behaviors": ["先听后读", "支持当前行推进", "教师确认跟读结果"],
        "open_source_dependencies": ["react", "svg", "webaudio"],
        "quality_gates": ["score_bound", "listen_before_read", "score_to_sound_mapping", "rhythm_value_check", "meter_bound", "teacher_confirm_ready"],
        "education_notes": ["小学高段简谱跟读要建立谱面和声音对应，不做脱离听觉的符号考试。"],
    },
    "melody_contour_line": {
        "version": "component_spec_v1",
        "component_id": "melody_contour_line",
        "name": "旋律线跟踪板",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg_webaudio",
        "layers": ["performance", "listening", "mixed"],
        "purpose": "把上行、下行、平稳等旋律走向转成可听、可看、可手势跟踪的 SVG 旋律线。",
        "student_actions": ["listen", "move", "sing", "explain"],
        "music_elements": ["旋律", "音高"],
        "required_material_entities": ["pitch_motion", "melody_phrase", "audio_clip"],
        "teacher_controls": ["replay", "show_hint", "hide_hint", "reset"],
        "required_elements": ["旋律线", "方向节点", "试听按钮", "手势选择", "唱回提示"],
        "behaviors": ["先听旋律再看线", "方向反馈回到上行/下行/平稳", "完成后回到唱回或听赏复听"],
        "open_source_dependencies": ["react", "svg", "webaudio"],
        "quality_gates": ["listen_before_trace", "pitch_direction_visible", "gesture_feedback_ready", "singing_transfer_ready"],
        "education_notes": ["旋律线描画要服务听觉和歌唱，不能只让学生看图猜上行下行。"],
    },
    "graphic_score_canvas": {
        "version": "component_spec_v1",
        "component_id": "graphic_score_canvas",
        "name": "图形谱创编板",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg_webaudio",
        "layers": ["creation", "performance", "mixed"],
        "purpose": "用点、线、块等图形表达高低、长短、强弱和播放顺序。",
        "student_actions": ["create", "listen", "revise", "explain"],
        "music_elements": ["图形谱", "音高", "力度", "节奏"],
        "required_material_entities": ["graphic_symbol_meanings"],
        "teacher_controls": ["play", "clear", "reset"],
        "required_elements": ["图形含义卡", "顺序格", "播放按钮", "记录导出"],
        "behaviors": ["图形必须绑定音乐含义", "放入顺序可回放", "展示前需要说明依据"],
        "open_source_dependencies": ["react", "svg", "webaudio"],
        "quality_gates": ["symbol_meaning_bound", "playback_ready", "sequence_complete", "evidence_required"],
        "education_notes": ["图形谱不是自由涂鸦，图形要和高低、长短、强弱等听觉经验建立对应。"],
    },
    "lyrics_strip": {
        "version": "component_spec_v1",
        "component_id": "lyrics_strip",
        "name": "歌词节奏条",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg",
        "layers": ["performance", "mixed"],
        "purpose": "把歌词分句、重音和节奏点转成学生可跟读、可跟唱的可视条。",
        "student_actions": ["listen", "read", "sing", "tap"],
        "music_elements": ["歌词", "乐句", "节奏"],
        "required_material_entities": ["lyrics_phrase"],
        "teacher_controls": ["phrase_loop", "hide_words", "show_pitch_hint", "reset"],
        "required_elements": ["歌词分句", "当前句高亮", "重音或节奏点"],
        "behaviors": ["支持隐藏关键词", "支持分句循环", "文字适合投屏"],
        "open_source_dependencies": ["react", "svg"],
        "quality_gates": ["lyrics_bound", "phrase_loop_ready", "readable_on_projector"],
        "education_notes": ["歌词节奏要先按稳定拍读，再回到歌曲演唱。"],
    },
    "form_card_timeline": {
        "version": "component_spec_v1",
        "component_id": "form_card_timeline",
        "name": "曲式卡时间线",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg",
        "layers": ["listening", "music_game", "mixed"],
        "purpose": "让学生把 A/B/C 段、重复和对比放到音频时间线上。",
        "student_actions": ["listen", "order", "explain"],
        "music_elements": ["曲式", "重复", "对比"],
        "required_material_entities": ["form_structure", "audio_clip"],
        "teacher_controls": ["replay_section", "show_hint", "reset"],
        "required_elements": ["段落卡", "时间线", "复听按钮"],
        "behaviors": ["绑定音频段落", "支持复听后排序", "要求说出结构依据"],
        "open_source_dependencies": ["react", "svg"],
        "quality_gates": ["audio_section_bound", "order_check_ready", "reason_prompt_ready"],
        "education_notes": ["曲式排序必须基于复听，不能凭空排列图形卡。"],
    },
    "theme_return_timeline": {
        "version": "component_spec_v1",
        "component_id": "theme_return_timeline",
        "name": "主题再现时间窗",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg_webaudio",
        "layers": ["listening", "music_game", "mixed"],
        "purpose": "把主题第一次出现和再现位置转成可复听、可记录的时间窗。",
        "student_actions": ["listen", "move", "explain"],
        "music_elements": ["主题", "重复", "再现"],
        "required_material_entities": ["audio_clip", "theme_windows"],
        "teacher_controls": ["replay", "replay_section", "show_hint", "reset"],
        "required_elements": ["主题时间窗", "当前复听位置", "主题标签", "记录出口"],
        "behaviors": ["必须先听主题", "动作时间绑定主题窗", "反馈回到旋律或节奏依据"],
        "open_source_dependencies": ["react", "webaudio"],
        "quality_gates": ["listen_before_action", "theme_window_bound", "evidence_required"],
        "education_notes": ["主题再现不是看时间点反应，学生要在复听中听到主题回来并说明依据。"],
    },
    "movement_action_cards": {
        "version": "component_spec_v1",
        "component_id": "movement_action_cards",
        "name": "复听动作卡",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react",
        "layers": ["listening", "performance", "music_game", "mixed"],
        "purpose": "用举卡、画圆、拍肩等动作把听到的主题、力度或结构变化外显出来。",
        "student_actions": ["listen", "move", "explain"],
        "music_elements": ["主题", "重复", "再现"],
        "required_material_entities": ["theme_windows"],
        "teacher_controls": ["show_hint", "hide_hint", "reset"],
        "required_elements": ["动作按钮", "选中状态", "音乐依据提示"],
        "behaviors": ["动作数量适合投屏", "不遮挡听赏材料", "动作结果可记录"],
        "open_source_dependencies": ["react"],
        "quality_gates": ["student_operable", "evidence_required", "teacher_reset_ready"],
        "education_notes": ["动作卡是听赏反应的外化工具，不能替代复听和音乐依据表达。"],
    },
    "instrument_card_grid": {
        "version": "component_spec_v1",
        "component_id": "instrument_card_grid",
        "name": "乐器卡网格",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react",
        "layers": ["listening", "music_game", "mixed"],
        "purpose": "支持乐器图片、音色词和声音材料的听辨匹配。",
        "student_actions": ["listen", "match", "explain"],
        "music_elements": ["音色", "乐器", "乐器家族"],
        "required_material_entities": ["instrument_pool", "timbre_set", "audio_clip"],
        "teacher_controls": ["replay", "show_family", "hide_picture", "reset"],
        "required_elements": ["乐器图卡", "音色词", "选择反馈"],
        "behaviors": ["先听声音再显示答案", "图片可以隐藏", "选择后说音色依据"],
        "open_source_dependencies": ["react", "radix"],
        "image2_required": True,
        "quality_gates": ["listen_before_choice", "asset_visible", "evidence_required"],
        "education_notes": ["音色游戏不能只看图猜乐器，必须绑定声音和证据词。"],
    },
    "meter_track": {
        "version": "component_spec_v1",
        "component_id": "meter_track",
        "name": "节拍轨道",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react_svg",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "用可视拍点帮助学生感受稳定拍、强弱拍和拍号。",
        "student_actions": ["listen", "tap", "move"],
        "music_elements": ["节拍", "强弱", "拍号"],
        "required_material_entities": ["meter"],
        "teacher_controls": ["tempo", "show_beat", "show_strong_beat", "reset"],
        "required_elements": ["拍点", "强拍标识", "BPM 同步"],
        "behaviors": ["强拍弱拍区分清晰", "低段少文字", "可调速"],
        "open_source_dependencies": ["react", "svg"],
        "quality_gates": ["meter_bound", "tempo_adjustable", "strong_beat_visible"],
        "education_notes": ["节拍轨道服务身体律动和稳拍体验，不是普通进度条。"],
    },
    "tap_feedback": {
        "version": "component_spec_v1",
        "component_id": "tap_feedback",
        "name": "敲击反馈",
        "audience": "primary_school",
        "role": "music_feedback",
        "runtime": "react_webaudio",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "把学生敲击转成早、准、晚、休止错误等形成性反馈。",
        "student_actions": ["tap", "revise"],
        "music_elements": ["节拍", "节奏", "休止"],
        "required_material_entities": ["rhythm_pattern", "meter"],
        "teacher_controls": ["show_beat", "reset"],
        "required_elements": ["即时反馈", "次数记录", "改进提示"],
        "behaviors": ["反馈指向音乐问题", "不只显示分数", "支持重置"],
        "open_source_dependencies": ["react", "webaudio"],
        "quality_gates": ["events_recorded", "timing_feedback_ready", "reset_ready"],
        "education_notes": ["节奏反馈要说明抢拍、拖拍、休止等音乐问题。"],
    },
    "body_action_cards": {
        "version": "component_spec_v1",
        "component_id": "body_action_cards",
        "name": "身体动作卡",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "用拍手、拍腿、跺脚、停住等动作表现节拍、强弱和休止。",
        "student_actions": ["move", "tap", "perform"],
        "music_elements": ["节拍", "节奏", "强弱", "休止"],
        "required_material_entities": ["rhythm_pattern", "meter"],
        "teacher_controls": ["tempo", "show_beat", "reset"],
        "required_elements": ["动作卡", "排序区", "节拍提示"],
        "behaviors": ["动作服务音乐结构", "低段可直接模仿", "组合后总拍数可检查"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["student_operable", "meter_bound", "rhythm_value_check", "sequence_reset_ready"],
        "education_notes": ["身体律动不是纯动作游戏，必须回到节拍和节奏。"],
    },
    "picture_prompt_cards": {
        "version": "component_spec_v1",
        "component_id": "picture_prompt_cards",
        "name": "图像提示卡",
        "audience": "primary_school",
        "role": "music_operation",
        "runtime": "react",
        "layers": ["listening", "mixed"],
        "purpose": "帮助低段学生听赏后选择情绪、形象或场景，并说理由。",
        "student_actions": ["listen", "choose", "explain"],
        "music_elements": ["情绪", "速度", "力度", "旋律"],
        "required_material_entities": ["expression_trait"],
        "teacher_controls": ["hide_words", "show_reason_prompt", "reset"],
        "required_elements": ["图片卡", "选择状态", "理由提示"],
        "behaviors": ["先听后选", "图卡文字可隐藏", "中段以上要求证据词"],
        "open_source_dependencies": ["react", "radix"],
        "image2_required": True,
        "quality_gates": ["asset_visible", "listen_before_choice", "reason_prompt_ready"],
        "education_notes": ["情绪图卡是听赏表达支架，不替代音乐聆听。"],
    },
    "teacher_control_bar": {
        "version": "component_spec_v1",
        "component_id": "teacher_control_bar",
        "name": "教师控制条",
        "audience": "primary_school",
        "role": "teacher_control",
        "runtime": "react_radix_lucide",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "让教师在课堂中调速、重置、隐藏提示、切换小组或确认结果。",
        "student_actions": ["observe"],
        "music_elements": ["课堂调控"],
        "required_material_entities": [],
        "teacher_controls": ["tempo", "hint_visibility", "reset", "group_control"],
        "required_elements": ["调速", "提示开关", "重置", "状态提示"],
        "behaviors": ["教师一键重置", "控制不遮挡学生操作", "按钮语义清晰"],
        "open_source_dependencies": ["react", "radix", "lucide-react"],
        "quality_gates": ["teacher_can_adjust", "reset_ready", "hint_toggle_ready"],
        "education_notes": ["教师控制是小学课堂可控性的必要条件，不能只给学生端。"],
    },
    "group_task_board": {
        "version": "component_spec_v1",
        "component_id": "group_task_board",
        "name": "小组任务板",
        "audience": "primary_school",
        "role": "classroom_management",
        "runtime": "react_radix",
        "layers": ["performance", "creation", "music_game", "mixed"],
        "purpose": "组织小组声部、接力、展示和合作任务。",
        "student_actions": ["cooperate", "perform", "assess"],
        "music_elements": ["合作", "声部", "展示"],
        "required_material_entities": ["classroom_group_task"],
        "teacher_controls": ["assign_group", "mark_done", "mute_group", "solo_group", "reset"],
        "required_elements": ["小组列表", "任务卡", "完成状态"],
        "behaviors": ["当前组清晰", "支持轮换", "支持完成记录"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["group_state_ready", "teacher_reset_ready", "task_bound"],
        "education_notes": ["小组任务必须围绕音乐声部、节奏或展示目标，而不是普通排队。"],
    },
    "rubric_panel": {
        "version": "component_spec_v1",
        "component_id": "rubric_panel",
        "name": "评价量规",
        "audience": "primary_school",
        "role": "music_feedback",
        "runtime": "react_radix",
        "layers": ["performance", "creation", "mixed"],
        "purpose": "记录学生或小组在节奏、演唱、合作、创编中的音乐表现。",
        "student_actions": ["assess", "explain"],
        "music_elements": ["评价", "合作", "表现"],
        "required_material_entities": ["assessment_criteria"],
        "teacher_controls": ["show_answer", "save", "reset"],
        "required_elements": ["评价维度", "选择状态", "记录输出"],
        "behaviors": ["评价维度对应音乐目标", "低段语言短", "可保存或复制结果"],
        "open_source_dependencies": ["react", "radix"],
        "quality_gates": ["criteria_bound", "record_ready", "teacher_save_ready"],
        "education_notes": ["评价必须回到音乐目标，不能只按通关速度排名。"],
    },
}


PRIMARY_COMPONENT_LIBRARY.update({
    "song_audio_workbench": {
        "version": "component_spec_v1",
        "component_id": "song_audio_workbench",
        "name": "音乐要素控制器",
        "audience": "primary_school",
        "role": "music_media_authoring",
        "runtime": "react_html_audio_webaudio_listening_pipeline",
        "layers": ["listening", "performance", "mixed"],
        "purpose": "复用现成聆听调音台，对课堂歌曲的主音、调式、速度、节奏密度和音色进行可听对比。",
        "student_actions": ["listen", "replay", "compare"],
        "music_elements": ["歌曲", "主音", "调式", "速度", "节奏密度", "音色"],
        "required_material_entities": ["audio_clip"],
        "teacher_controls": ["upload", "tonic", "mode", "tempo", "rhythm_density", "instrument", "reset"],
        "required_elements": ["素材来源", "主音", "调式", "速度倍率", "节奏密度", "音色", "原版与变化版播放器"],
        "behaviors": ["教师指定材料优先", "同一歌曲复用解析缓存", "原版与变化版可对比", "处理限制和版权状态可见"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text"],
        "empty_state": "没有合法音频时提示上传或选择平台授权资源。",
        "error_state": "音频处理失败时显示原因并禁止进入正式训练。",
        "fixture": {"tonic": "C", "mode": "preserve", "tempo_multiplier": 1.0, "rhythm_density": "preserve", "instrument": "preserve"},
        "called_by_template_ids": ["phrase_loop_core", "lyrics_rhythm_core"],
        "open_source_dependencies": ["react", "webaudio", "ffmpeg"],
        "quality_gates": ["not_standalone_game", "rights_source_visible", "audio_playable", "teacher_confirm_boundary"],
        "education_notes": ["控制器用于突出一个音乐要素并进行听觉比较，不用技术处理替代教师的音乐判断。"],
    },
    "score_audio_sync_player": {
        "version": "component_spec_v1",
        "component_id": "score_audio_sync_player",
        "name": "谱面与声音同步播放器",
        "audience": "primary_school",
        "role": "score_playback",
        "runtime": "react_svg_webaudio_musicxml",
        "layers": ["listening", "performance", "mixed"],
        "purpose": "让五线谱、简谱、歌词光标和声音读取同一条已确认时间轴。",
        "student_actions": ["listen", "track", "read", "sing"],
        "music_elements": ["识谱", "旋律", "节奏", "歌词"],
        "required_material_entities": ["melody_phrase", "audio_clip"],
        "teacher_controls": ["play", "pause", "seek", "loop", "score_view", "reset"],
        "required_elements": ["五线谱", "简谱", "同步光标", "乐句循环", "确认状态"],
        "behaviors": ["谱音同源", "草稿需教师确认", "点击谱面定位", "多声部可独奏"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text"],
        "empty_state": "缺少已确认谱面时显示材料阻断提示。",
        "error_state": "谱面与音频无法对齐时禁止标记为同步完成。",
        "fixture": {"view": "numbered", "teacher_confirmed": True},
        "called_by_template_ids": ["simple_score_core", "phrase_loop_core"],
        "open_source_dependencies": ["react", "svg", "opensheetmusicdisplay"],
        "quality_gates": ["not_standalone_game", "score_to_sound_mapping", "teacher_confirm_boundary"],
        "education_notes": ["识谱必须回到声音，不能形成脱离听觉的符号操作。"],
    },
    "ear_training_engine": {
        "version": "component_spec_v1",
        "component_id": "ear_training_engine",
        "name": "视唱练耳引擎",
        "audience": "primary_school",
        "role": "music_training_engine",
        "runtime": "react_webaudio",
        "layers": ["listening", "performance", "music_game", "mixed"],
        "purpose": "提供受教师材料与难度约束的单音、音程、节奏、短旋律和调式训练。",
        "student_actions": ["listen", "choose", "tap", "sing", "explain"],
        "music_elements": ["音高", "音程", "节奏", "旋律", "调式"],
        "required_material_entities": ["solfege_set", "rhythm_pattern"],
        "teacher_controls": ["question_type", "pitch_range", "solfege_system", "random_policy", "reset"],
        "required_elements": ["听题", "客观作答", "即时反馈", "唱回确认", "教师约束"],
        "behaviors": ["默认首调", "仅在教师允许时随机", "客观输入自动判断", "演唱由教师确认"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text", "keyboard_optional"],
        "empty_state": "没有教师材料或出题范围时等待配置。",
        "error_state": "真实声音加载失败时不使用振荡器替代。",
        "fixture": {"question_type": "single_pitch", "solfege_system": "movable_do"},
        "called_by_template_ids": ["solfege_echo_core", "rhythm_echo_core"],
        "open_source_dependencies": ["react", "webaudio", "soundfont-player"],
        "quality_gates": ["not_standalone_game", "teacher_material_priority", "teacher_confirm_boundary"],
        "education_notes": ["网页判断客观答案，真实视唱和模唱由教师确认。"],
    },
    "vocal_choir_training": {
        "version": "component_spec_v1",
        "component_id": "vocal_choir_training",
        "name": "合唱与嗓音训练组件",
        "audience": "primary_school",
        "role": "guided_vocal_practice",
        "runtime": "react_webaudio_mediarecorder",
        "layers": ["performance", "mixed"],
        "purpose": "按儿童嗓音安全边界组织听、准备、发声、乐句练习、回听和教师反馈。",
        "student_actions": ["listen", "breathe", "sing", "replay", "revise"],
        "music_elements": ["音高", "气息", "乐句", "合唱"],
        "required_material_entities": ["melody_phrase", "audio_clip"],
        "teacher_controls": ["grade_preset", "range", "loop", "record", "confirm", "reset"],
        "required_elements": ["儿童安全提示", "五步训练", "音高趋势", "本机回听", "教师确认"],
        "behaviors": ["不鼓励喊唱", "限制连续练习", "录音仅本机会话", "不自动定级"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text"],
        "empty_state": "没有已确认乐句时不生成嗓音训练任务。",
        "error_state": "麦克风不可用时保留教师现场确认流程。",
        "fixture": {"grade_preset": "middle_primary", "recording_policy": "local_session_only"},
        "called_by_template_ids": ["phrase_loop_core", "solfege_echo_core"],
        "open_source_dependencies": ["react", "webaudio", "mediarecorder"],
        "quality_gates": ["not_standalone_game", "child_voice_safety", "local_recording_only", "teacher_confirm_boundary"],
        "education_notes": ["音色、气息、咬字、融合和音乐表现必须由教师专业判断。"],
    },
    "ensemble_conductor": {
        "version": "component_spec_v1",
        "component_id": "ensemble_conductor",
        "name": "多声部排练与指挥台",
        "audience": "primary_school",
        "role": "ensemble_rehearsal",
        "runtime": "react_webaudio_multitrack",
        "layers": ["performance", "mixed"],
        "purpose": "支持儿童二声部、轮唱、奥尔夫和课堂乐队的分轨排练与进入指挥。",
        "student_actions": ["listen", "enter", "perform", "cooperate", "assess"],
        "music_elements": ["多声部", "节奏", "合作", "力度"],
        "required_material_entities": ["classroom_group_task", "audio_clip"],
        "teacher_controls": ["mute", "solo", "volume", "loop", "entry_cue", "reset"],
        "required_elements": ["声部轨道", "静音独奏", "小节循环", "进入提示", "全屏指挥"],
        "behaviors": ["人声与乐器代奏明确标注", "预备拍不占正式时间轴", "按声部练习", "教师评价平衡与合作"],
        "interaction_modes": ["desktop_mouse", "touch_screen", "projector_large_text"],
        "empty_state": "没有分轨或已确认谱面时提示教师补充材料。",
        "error_state": "任何声部加载失败时标记该声部，不伪装完整合奏。",
        "fixture": {"parts": ["声部一", "声部二"], "count_in_bars": 1},
        "called_by_template_ids": ["orff_ensemble_core", "classroom_band_core"],
        "open_source_dependencies": ["react", "webaudio", "soundfont-player"],
        "quality_gates": ["not_standalone_game", "part_source_labeled", "teacher_confirm_boundary"],
        "education_notes": ["网页辅助进入与节奏证据，声部平衡、音准和表现由教师判断。"],
    },
})


LEGACY_COMPONENT_LIBRARY: dict[str, dict[str, Any]] = {
    "audio_upload_compare": {
        "name": "音频上传与对比播放器",
        "layers": ["listening", "mixed"],
        "purpose": "让教师或学生上传音频，并在原始版本和改编版本之间进行课堂对比聆听。",
        "required_elements": ["音频上传入口", "原始版本试听", "改编版本试听", "对比提示卡"],
        "behaviors": ["上传后显示处理状态", "支持原始/改编切换", "引导学生描述听觉变化"],
    },
    "element_control_panel": {
        "name": "音乐要素控制面板",
        "layers": ["listening", "mixed"],
        "purpose": "把调性、调式、节奏密度、速度和音色变成学生可直接操作的课堂按钮或控件。",
        "required_elements": ["调性选择", "调式选择", "节奏选择", "速度控制", "音色选择"],
        "behaviors": ["每次突出一个要素变化", "提供重置按钮", "展示当前选择摘要"],
    },
    "level_map": {
        "name": "关卡地图",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "把表现任务组织成可解锁的闯关路径，帮助学生理解课堂进度。",
        "required_elements": ["关卡节点", "当前关卡状态", "已通关标记", "继续挑战按钮"],
        "behaviors": ["按顺序解锁", "保存进度", "支持回看已通关关卡"],
    },
    "countdown_start": {
        "name": "倒计时开始流程",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "统一挑战开始顺序，避免学生先播放、后敲击或提前操作造成计时混乱。",
        "required_elements": ["开始挑战按钮", "4 拍倒计时", "开始提示", "重置按钮"],
        "behaviors": ["点击开始后进入准备状态", "倒计时结束才开始记录", "重置时取消倒计时"],
    },
    "rhythm_tap_pads": {
        "name": "节奏敲击垫",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "提供鼓、镲、拍手等可点击/触摸的节奏表现入口。",
        "required_elements": ["可点击乐器垫", "当前目标提示", "敲击动画", "音色反馈"],
        "behaviors": ["支持鼠标和触摸", "记录敲击顺序", "挑战中才计入成绩"],
    },
    "timing_feedback": {
        "name": "节拍即时反馈",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "对学生的敲击、模仿或表现给出可理解的即时反馈。",
        "required_elements": ["正确提示", "过早提示", "过晚提示", "乐器错误提示"],
        "behaviors": ["按评价维度显示反馈", "给出下一次改进建议", "挑战结束生成小结"],
    },
    "badge_progress": {
        "name": "徽章与通关进度",
        "layers": ["performance", "music_game", "mixed"],
        "purpose": "通过徽章、星级或能量条增强闯关成就感。",
        "required_elements": ["徽章展示", "星级评价", "进度条", "通关弹窗"],
        "behaviors": ["通关后点亮徽章", "显示下一关入口", "支持重置全部进度"],
    },
    "drag_drop_puzzle": {
        "name": "音乐素材拖拽拼图",
        "layers": ["creation", "music_game", "mixed"],
        "purpose": "让学生拖拽音高、节奏或乐句素材，拼成自己的音乐想法。",
        "required_elements": ["素材仓库", "作品区", "拖拽/点击添加", "结构反馈"],
        "behaviors": ["支持移除素材", "提示开始/发展/收束", "可一键清空"],
    },
    "melody_grid": {
        "name": "网格旋律线",
        "layers": ["creation", "mixed"],
        "purpose": "让学生在网格中画旋律线，横轴为十六分音符，纵轴为半音并显示首调唱名。",
        "required_elements": ["调性选择", "小节数选择", "半音网格", "首调唱名标签"],
        "behaviors": ["点击或拖动画线", "补齐中间格点", "合并连续同音", "支持重画"],
    },
    "voice_instrument_mixer": {
        "name": "声部与音色混合器",
        "layers": ["creation", "mixed"],
        "purpose": "支持双声部创作，并为不同声部分配不同音色。",
        "required_elements": ["声部切换", "声部一音色", "声部二音色", "当前声部标记"],
        "behaviors": ["不同声部用不同颜色", "分别播放或合奏", "声部数据互不覆盖"],
    },
    "playback_controls": {
        "name": "试听与重置控制",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "提供清晰的播放、暂停、重置、试听作品等基础控制。",
        "required_elements": ["播放按钮", "停止按钮", "重置按钮", "播放状态提示"],
        "behaviors": ["避免重复播放冲突", "播放时更新状态", "重置时清空临时数据"],
    },
    "reflection_panel": {
        "name": "课堂反思与教师提示",
        "layers": ["listening", "performance", "creation", "music_game", "mixed"],
        "purpose": "把学生操作转化为可讨论的音乐语言和课堂评价。",
        "required_elements": ["学生问题", "教师提示", "评价维度", "展示建议"],
        "behaviors": ["根据当前活动显示问题", "完成后生成总结语", "提示下一步课堂讨论"],
    },
}


COMPONENT_LIBRARY: dict[str, dict[str, Any]] = {
    **PRIMARY_COMPONENT_LIBRARY,
    **LEGACY_COMPONENT_LIBRARY,
}


INTERACTION_COMPONENTS = {
    "rhythm_tap_challenge": ["level_map", "countdown_start", "rhythm_tap_pads", "timing_feedback", "badge_progress"],
    "listening_quiz_challenge": ["level_map", "audio_upload_compare", "timing_feedback", "badge_progress"],
    "body_percussion_challenge": ["level_map", "countdown_start", "timing_feedback", "badge_progress", "reflection_panel"],
    "call_response_singing": ["level_map", "countdown_start", "timing_feedback", "badge_progress", "reflection_panel"],
    "level_map_challenge": ["level_map", "countdown_start", "timing_feedback", "badge_progress"],
    "two_voice_melody_grid": ["melody_grid", "voice_instrument_mixer", "playback_controls", "reflection_panel"],
    "melody_grid_composer": ["melody_grid", "playback_controls", "reflection_panel"],
    "melody_continuation_board": ["drag_drop_puzzle", "playback_controls", "reflection_panel"],
    "note_fill_blank_puzzle": ["drag_drop_puzzle", "timing_feedback", "playback_controls"],
    "drag_drop_music_puzzle": ["drag_drop_puzzle", "playback_controls", "reflection_panel"],
    "element_transform_lab": ["audio_upload_compare", "element_control_panel", "playback_controls", "reflection_panel"],
    "rhythm_race_game": ["countdown_start", "drag_drop_puzzle", "playback_controls", "timing_feedback", "badge_progress"],
    "rhythm_animal_race": ["countdown_start", "drag_drop_puzzle", "playback_controls", "timing_feedback", "badge_progress"],
    "pitch_flying_game": ["playback_controls", "timing_feedback", "badge_progress", "reflection_panel"],
    "melody_path_game": ["drag_drop_puzzle", "playback_controls", "timing_feedback", "badge_progress", "reflection_panel"],
    "music_match_game": ["drag_drop_puzzle", "timing_feedback", "badge_progress", "reflection_panel"],
    "timbre_detective_game": ["drag_drop_puzzle", "timing_feedback", "badge_progress", "reflection_panel"],
    "pentatonic_grid_game": ["drag_drop_puzzle", "playback_controls", "timing_feedback", "badge_progress", "reflection_panel"],
    "group_relay_game": ["level_map", "countdown_start", "timing_feedback", "badge_progress", "reflection_panel"],
    "expression_control_game": ["playback_controls", "timing_feedback", "badge_progress", "reflection_panel"],
    "lesson_mission_game": ["level_map", "drag_drop_puzzle", "timing_feedback", "badge_progress", "reflection_panel"],
    "custom_music_game": ["drag_drop_puzzle", "playback_controls", "timing_feedback", "badge_progress", "reflection_panel"],
    "three_phase_music_studio": [
        "audio_upload_compare",
        "element_control_panel",
        "level_map",
        "drag_drop_puzzle",
        "playback_controls",
        "reflection_panel",
    ],
}


COMPONENT_ALIASES = {
    "audio_upload": "audio_upload_compare",
    "compare_player": "audio_upload_compare",
    "element_controls": "element_control_panel",
    "listening_lab": "audio_upload_compare",
    "listening_prompt_cards": "reflection_panel",
    "audio_choice_cards": "audio_upload_compare",
    "answer_feedback": "timing_feedback",
    "countdown": "countdown_start",
    "tap_pads": "rhythm_tap_pads",
    "badge_unlock": "badge_progress",
    "challenge_panel": "level_map",
    "completion_feedback": "timing_feedback",
    "movement_cards": "timing_feedback",
    "group_checklist": "reflection_panel",
    "phrase_prompt": "reflection_panel",
    "record_or_confirm": "timing_feedback",
    "teacher_check": "reflection_panel",
    "piece_bank": "drag_drop_puzzle",
    "drop_zone": "drag_drop_puzzle",
    "structure_feedback": "reflection_panel",
    "voice_switcher": "voice_instrument_mixer",
    "instrument_selector": "voice_instrument_mixer",
    "key_selector": "melody_grid",
    "save_reset": "playback_controls",
    "phrase_seed": "drag_drop_puzzle",
    "continuation_slots": "drag_drop_puzzle",
    "note_slots": "drag_drop_puzzle",
    "draggable_notes": "drag_drop_puzzle",
    "instant_check": "timing_feedback",
    "phase_tabs": "level_map",
    "creation_board": "drag_drop_puzzle",
    "feedback_card": "reflection_panel",
    "reset_button": "playback_controls",
    "character_cards": "drag_drop_puzzle",
    "game_cards": "drag_drop_puzzle",
    "race_lane": "playback_controls",
    "runner_strip": "playback_controls",
    "game_feedback": "timing_feedback",
    "score_panel": "badge_progress",
    "retry_controls": "playback_controls",
}


def list_component_library() -> list[dict[str, Any]]:
    return [_component_payload(component_id, component) for component_id, component in COMPONENT_LIBRARY.items()]


def get_component_spec(component_id: str) -> dict[str, Any]:
    raw_id = str(component_id or "")
    canonical = raw_id if raw_id in COMPONENT_LIBRARY else COMPONENT_ALIASES.get(raw_id, raw_id)
    component = COMPONENT_LIBRARY.get(canonical)
    if not component:
        raise ValueError(f"unknown component: {component_id}")
    return _component_payload(canonical, component)


def components_for_interaction(interaction: str) -> list[str]:
    return INTERACTION_COMPONENTS.get(interaction, ["level_map", "timing_feedback", "reflection_panel"])


def normalize_component_ids(component_ids: list[str]) -> list[str]:
    normalized: list[str] = []
    for component_id in component_ids:
        canonical = component_id if component_id in COMPONENT_LIBRARY else COMPONENT_ALIASES.get(component_id, component_id)
        if canonical in COMPONENT_LIBRARY and canonical not in normalized:
            normalized.append(canonical)
    return normalized


def component_specs_for_ids(component_ids: list[str]) -> list[dict[str, Any]]:
    return [
        _component_payload(component_id, COMPONENT_LIBRARY[component_id])
        for component_id in normalize_component_ids(component_ids)
    ]


def component_prompt_catalog() -> list[dict[str, Any]]:
    return [
        {
            "id": component_id,
            "name": component["name"],
            "layers": component["layers"],
            "purpose": component["purpose"],
            "required_elements": component["required_elements"],
        }
        for component_id, component in COMPONENT_LIBRARY.items()
    ]


def _component_payload(component_id: str, component: dict[str, Any]) -> dict[str, Any]:
    payload = {"id": component_id, "component_id": component_id, **component}
    if "version" not in payload:
        payload["version"] = "legacy_component_spec_v1"
    if "audience" not in payload:
        payload["audience"] = "mixed"
    if "runtime" not in payload:
        payload["runtime"] = "react"
    if "role" not in payload:
        payload["role"] = "legacy_generation_component"
    if "student_actions" not in payload:
        payload["student_actions"] = []
    if "music_elements" not in payload:
        payload["music_elements"] = []
    if "required_material_entities" not in payload:
        payload["required_material_entities"] = []
    if "teacher_controls" not in payload:
        payload["teacher_controls"] = []
    if "open_source_dependencies" not in payload:
        payload["open_source_dependencies"] = []
    if "quality_gates" not in payload:
        payload["quality_gates"] = []
    if "education_notes" not in payload:
        payload["education_notes"] = []
    return payload
