from __future__ import annotations

from copy import deepcopy
from typing import Any


REQUIRED_GAMEPLAY_TEMPLATE_FIELDS = (
    "version",
    "template_id",
    "label",
    "audience",
    "primary_competency",
    "music_elements",
    "student_practices",
    "teaching_stages",
    "supported_materials",
    "core_loop",
    "required_components",
    "required_rules",
    "required_teacher_controls",
    "optional_assets",
    "difficulty_controls",
    "quality_gates",
    "education_alignment",
    "implementation_status",
    "evidence",
    "applicable_activity_ids",
)


def _spec(
    template_id: str,
    label: str,
    *,
    primary_competency: str,
    student_practices: list[str],
    music_elements: list[str],
    teaching_stages: list[str],
    supported_materials: list[str],
    core_loop: list[str],
    required_components: list[str],
    required_rules: list[str],
    required_teacher_controls: list[str],
    optional_assets: list[str],
    difficulty_controls: list[str],
    applicable_activity_ids: list[str],
    implementation_status: str,
    evidence: list[str],
    grade_fit: dict[str, str],
    pedagogy_notes: list[str],
    secondary_competency: str = "",
) -> dict[str, Any]:
    return {
        "version": "gameplay_template_spec_v1",
        "template_id": template_id,
        "label": label,
        "audience": "primary_school",
        "primary_competency": primary_competency,
        "secondary_competency": secondary_competency,
        "music_elements": music_elements,
        "student_practices": student_practices,
        "teaching_stages": teaching_stages,
        "supported_materials": supported_materials,
        "core_loop": core_loop,
        "required_components": required_components,
        "required_rules": required_rules,
        "required_teacher_controls": required_teacher_controls,
        "optional_assets": optional_assets,
        "difficulty_controls": difficulty_controls,
        "quality_gates": ["playable_or_status_marked", "material_bound", "teacher_can_adjust", "student_music_practice_visible"],
        "education_alignment": {
            "primary_competency": primary_competency,
            "secondary_competency": secondary_competency,
            "student_practices": student_practices,
            "music_elements": music_elements,
            "teaching_stages": teaching_stages,
            "grade_fit": grade_fit,
            "pedagogy_notes": pedagogy_notes,
        },
        "implementation_status": implementation_status,
        "evidence": evidence,
        "applicable_activity_ids": applicable_activity_ids,
    }


RUNTIME_READY = "runtime_ready"
ACTIVITY_READY = "activity_ready"
SPEC_READY = "spec_ready"


GAMEPLAY_TEMPLATE_CATALOG: dict[str, dict[str, Any]] = {
    "rhythm_echo_core": _spec(
        "rhythm_echo_core",
        "节奏复刻",
        primary_competency="艺术表现",
        secondary_competency="审美感知",
        student_practices=["listen", "tap", "move"],
        music_elements=["稳定拍", "节奏", "休止"],
        teaching_stages=["律动/节奏", "复习巩固"],
        supported_materials=["rhythm_pattern", "meter", "bpm"],
        core_loop=["listen", "remember", "tap", "feedback"],
        required_components=["audio_player", "meter_track", "rhythm_pad", "tap_feedback"],
        required_rules=["rhythm_timing_judgement", "rest_guard_rule"],
        required_teacher_controls=["tempo_control_pack", "hint_visibility_pack", "reset_pack"],
        optional_assets=["reward_badge_pack", "classroom_stage_background_pack"],
        difficulty_controls=["bpm", "pattern_length", "show_hint", "repeat_count"],
        applicable_activity_ids=["rhythm_warmup", "rhythm_question_answer", "lyrics_rhythm_reading"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser RhythmEchoScene", "frontend tests", "browser smoke"],
        grade_fit={
            "lower_primary": "短节奏、强图形提示、先听再拍。",
            "middle_primary": "加入四分、八分和休止的组合复刻。",
            "upper_primary": "可隐藏提示并要求说出节奏疏密依据。",
        },
        pedagogy_notes=["节奏复刻必须先听一遍再拍回来。", "休止要作为停住的音乐表现反馈。"],
    ),
    "beat_guardian_core": _spec(
        "beat_guardian_core",
        "强拍守卫",
        primary_competency="艺术表现",
        secondary_competency="审美感知",
        student_practices=["listen", "tap", "move", "play"],
        music_elements=["节拍", "拍号", "强弱"],
        teaching_stages=["律动/节奏"],
        supported_materials=["meter", "bpm", "accent_pattern"],
        core_loop=["listen_meter", "predict_strong_beat", "tap_or_play", "feedback"],
        required_components=["meter_track", "tap_feedback", "virtual_hand_drum", "teacher_control_bar"],
        required_rules=["meter_accent_rule", "rhythm_timing_judgement"],
        required_teacher_controls=["tempo_control_pack", "hint_visibility_pack", "reset_pack"],
        optional_assets=["body_action_card_pack", "classroom_stage_background_pack"],
        difficulty_controls=["bpm", "meter", "show_strong_beat", "target_beats"],
        applicable_activity_ids=["meter_body_movement", "strong_weak_beat_circle", "rhythm_warmup"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser BeatGuardianScene", "strong/weak beat React activity"],
        grade_fit={
            "lower_primary": "用大动作找第 1 拍，不先讲抽象拍号。",
            "middle_primary": "比较二拍子、三拍子的强弱规律。",
            "upper_primary": "可加入更长小节周期和弱拍蓄势。",
        },
        pedagogy_notes=["强拍活动先体验强弱，再进入术语。", "判定围绕拍点同步，不按抢答速度给分。"],
    ),
    "rhythm_chain_core": _spec(
        "rhythm_chain_core",
        "节奏接龙",
        primary_competency="艺术表现",
        student_practices=["listen", "tap", "cooperate"],
        music_elements=["节奏", "乐句", "合作"],
        teaching_stages=["节奏练习", "小组合作"],
        supported_materials=["rhythm_pattern", "meter", "group_tasks"],
        core_loop=["group_a_play", "group_b_echo", "rotate", "record"],
        required_components=["rhythm_card_bank", "group_task_board", "meter_track"],
        required_rules=["rhythm_pattern_order_rule", "group_turn_rule"],
        required_teacher_controls=["group_rotation_pack", "tempo_control_pack", "reset_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["pattern_length", "group_count", "hint_visibility"],
        applicable_activity_ids=["rhythm_question_answer", "group_relay_performance"],
        implementation_status=SPEC_READY,
        evidence=["spec catalog", "micro activity two_group_echo covers classroom form"],
        grade_fit={"lower_primary": "两组短问答。", "middle_primary": "四小组节奏接龙。", "upper_primary": "加入问答句平衡。"},
        pedagogy_notes=["接龙要保持同拍号和稳定拍。", "小组轮换不能打断音乐流程。"],
    ),
    "body_percussion_core": _spec(
        "body_percussion_core",
        "身体打击工坊",
        primary_competency="创意实践",
        secondary_competency="艺术表现",
        student_practices=["move", "tap", "create"],
        music_elements=["节奏", "节拍", "力度"],
        teaching_stages=["律动", "创编"],
        supported_materials=["meter", "body_action_set", "rhythm_pattern"],
        core_loop=["choose_action", "arrange", "perform", "revise"],
        required_components=["body_action_cards", "meter_track", "tap_feedback"],
        required_rules=["bar_length_rule", "creation_bar_fit_rule"],
        required_teacher_controls=["teacher_confirm_pack", "reset_pack"],
        optional_assets=["body_action_card_pack", "reward_badge_pack"],
        difficulty_controls=["bar_count", "action_count", "show_hint"],
        applicable_activity_ids=["body_percussion_builder", "steady_beat_walk", "strong_weak_beat_circle"],
        implementation_status=ACTIVITY_READY,
        evidence=["独立 React 学生活动页", "body percussion frontend tests"],
        grade_fit={"lower_primary": "拍手、拍腿、跺脚三类动作。", "middle_primary": "加入力度和休止。", "upper_primary": "可做小组身体打击编排。"},
        pedagogy_notes=["身体动作服务节奏和强弱，不做纯动作奖励。", "创编必须能回放或表演验证。"],
    ),
    "solfege_target_core": _spec(
        "solfege_target_core",
        "唱名打靶",
        primary_competency="艺术表现",
        student_practices=["listen", "sing", "read"],
        music_elements=["音高", "唱名", "音级"],
        teaching_stages=["音高练习", "学唱准备"],
        supported_materials=["solfege_set", "pitch_set", "audio_clip"],
        core_loop=["listen_note", "choose_solfege", "sing_back", "feedback"],
        required_components=["audio_player", "solfege_card_bank", "teacher_control_bar"],
        required_rules=["solfege_match_rule", "singback_teacher_confirm_rule"],
        required_teacher_controls=["teacher_confirm_pack", "hint_visibility_pack", "reset_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["pitch_count", "show_hint", "repeat_count"],
        applicable_activity_ids=["solfege_sorting", "solfege_echo_singing", "simple_score_following"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser SolfegeTargetScene", "solfege echo activity"],
        grade_fit={"lower_primary": "少量唱名听辨和模唱。", "middle_primary": "do/re/mi/sol/la 排列。", "upper_primary": "可加入简谱提示。"},
        pedagogy_notes=["唱名活动要从听和唱开始。", "儿童唱回优先教师确认。"],
    ),
    "pitch_ladder_core": _spec(
        "pitch_ladder_core",
        "音高爬梯",
        primary_competency="审美感知",
        student_practices=["listen", "sing", "read"],
        music_elements=["音高", "旋律", "级进"],
        teaching_stages=["音高练习"],
        supported_materials=["pitch_motion", "melody_phrase", "solfege_set"],
        core_loop=["listen", "judge_direction", "move_on_ladder", "sing_back"],
        required_components=["audio_player", "pitch_ladder", "solfege_card_bank"],
        required_rules=["pitch_direction_rule", "solfege_match_rule"],
        required_teacher_controls=["hint_visibility_pack", "reset_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["note_count", "direction_mix", "show_hint"],
        applicable_activity_ids=["melody_contour_trace", "solfege_sorting", "simple_score_following"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser PitchLadderScene", "melody contour activity"],
        grade_fit={"lower_primary": "高低、上行、下行。", "middle_primary": "级进和跳进。", "upper_primary": "简谱和短旋律走向。"},
        pedagogy_notes=["先听旋律走向，再用路线或手势表达。", "不要把音高活动变成纯视觉排序。"],
    ),
    "xylophone_play_core": _spec(
        "xylophone_play_core",
        "音条琴挑战",
        primary_competency="艺术表现",
        secondary_competency="创意实践",
        student_practices=["play", "listen", "sing"],
        music_elements=["音高", "旋律", "五声音阶"],
        teaching_stages=["器乐", "创编"],
        supported_materials=["solfege_set", "pentatonic_scale", "melody_frame"],
        core_loop=["listen_target", "play_notes", "compare", "retry"],
        required_components=["virtual_xylophone", "solfege_card_bank", "audio_player"],
        required_rules=["melody_sequence_rule", "pentatonic_constraint_rule"],
        required_teacher_controls=["tempo_control_pack", "teacher_confirm_pack", "reset_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["note_count", "allowed_notes", "show_hint"],
        applicable_activity_ids=["xylophone_creation", "solfege_sorting"],
        implementation_status=ACTIVITY_READY,
        evidence=["五声音条琴创编 React 活动页", "composition_puzzle_core runtime carrier"],
        grade_fit={"lower_primary": "不建议复杂音条琴挑战。", "middle_primary": "少量 do/re/mi/sol/la。", "upper_primary": "五声音阶短句演奏。"},
        pedagogy_notes=["虚拟音条琴要限制音级，避免乱敲。", "演奏后要听回并修正。"],
    ),
    "timbre_detective_core": _spec(
        "timbre_detective_core",
        "音色侦探",
        primary_competency="审美感知",
        student_practices=["listen", "match", "explain"],
        music_elements=["音色", "乐器", "发声方式"],
        teaching_stages=["欣赏复听", "复听/探究"],
        supported_materials=["instrument_pool", "audio_clip", "timbre_words"],
        core_loop=["listen_sound", "choose_instrument", "choose_evidence", "feedback"],
        required_components=["compare_player", "instrument_card_grid", "evidence_word_cards"],
        required_rules=["timbre_match_rule", "timbre_evidence_rule"],
        required_teacher_controls=["playback_control_pack", "teacher_confirm_pack", "reset_pack"],
        optional_assets=["generated_playable_instrument_pack", "reward_badge_pack"],
        difficulty_controls=["instrument_count", "show_image_hint", "relisten_count"],
        applicable_activity_ids=["instrument_timbre_match", "instrument_family_sorting", "listen_choose_explain"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser TimbreDetectiveScene", "生成式可演奏乐器皮肤包"],
        grade_fit={"lower_primary": "少量强对比音色。", "middle_primary": "乐器音色和证据词。", "upper_primary": "发声方式和文化拓展。"},
        pedagogy_notes=["音色活动必须先听声音。", "图片只能辅助，不能替代音频证据。"],
    ),
    "instrument_family_sort_core": _spec(
        "instrument_family_sort_core",
        "乐器家族分类",
        primary_competency="文化理解",
        secondary_competency="审美感知",
        student_practices=["listen", "classify", "explain"],
        music_elements=["乐器家族", "音色", "发声方式"],
        teaching_stages=["欣赏", "拓展"],
        supported_materials=["instrument_pool", "instrument_family_set", "audio_clip"],
        core_loop=["listen", "inspect_generated_skin", "classify", "explain"],
        required_components=["instrument_card_grid", "compare_player", "evidence_word_cards"],
        required_rules=["instrument_family_rule", "timbre_evidence_rule"],
        required_teacher_controls=["playback_control_pack", "teacher_confirm_pack", "reset_pack"],
        optional_assets=["generated_playable_instrument_pack"],
        difficulty_controls=["family_count", "instrument_count", "show_family_hint"],
        applicable_activity_ids=["instrument_family_sorting", "instrument_timbre_match"],
        implementation_status=ACTIVITY_READY,
        evidence=["独立 React 学生活动页", "生成式可演奏乐器皮肤包", "真实采样播放合同"],
        grade_fit={"lower_primary": "不做复杂家族分类。", "middle_primary": "吹奏、拉弦、弹拨、打击。", "upper_primary": "民族/西洋与发声方式联系。"},
        pedagogy_notes=["分类前必须先听声音。", "生成乐器皮肤只辅助操作和验证，分类依据必须回到采样声音。"],
    ),
    "listening_choice_core": _spec(
        "listening_choice_core",
        "听赏选择",
        primary_competency="审美感知",
        student_practices=["listen", "choose", "explain"],
        music_elements=["情绪", "速度", "力度"],
        teaching_stages=["导入", "初听/感受"],
        supported_materials=["audio_clip", "accepted_moods", "evidence_terms"],
        core_loop=["listen_once", "choose_mood", "choose_evidence", "share"],
        required_components=["audio_player", "choice_cards", "rubric_panel"],
        required_rules=["mood_choice_rule", "tempo_dynamic_choice_rule"],
        required_teacher_controls=["playback_control_pack", "result_review_pack", "reset_pack"],
        optional_assets=["music_mood_picture_pack", "mood_symbol_card_pack"],
        difficulty_controls=["choice_count", "evidence_required", "relisten_count"],
        applicable_activity_ids=["picture_listening_intro", "listen_choose_explain", "lesson_opening_hook"],
        implementation_status=ACTIVITY_READY,
        evidence=["听赏情绪选择 React 活动页", "music_mood_picture_pack image_gen PNG 已入库", "mood_symbol_card_pack fallback"],
        grade_fit={"lower_primary": "图片表达感受。", "middle_primary": "加入速度、力度证据词。", "upper_primary": "要求复听验证依据。"},
        pedagogy_notes=["欣赏选择必须先完整聆听。", "选择之后要说音乐依据。"],
    ),
    "form_treasure_core": _spec(
        "form_treasure_core",
        "曲式寻宝",
        primary_competency="审美感知",
        student_practices=["listen", "order", "explain"],
        music_elements=["曲式", "重复", "对比"],
        teaching_stages=["欣赏复听", "高段探究"],
        supported_materials=["form_structure", "audio_segments", "theme_labels"],
        core_loop=["listen_segments", "order_cards", "explain_repeat_contrast", "verify"],
        required_components=["audio_player", "form_card_timeline", "rubric_panel"],
        required_rules=["form_order_rule", "theme_return_window_rule"],
        required_teacher_controls=["playback_control_pack", "hint_visibility_pack", "reset_pack"],
        optional_assets=["form_shape_card_pack"],
        difficulty_controls=["segment_count", "show_labels", "relisten_count"],
        applicable_activity_ids=["form_ordering", "theme_return_action"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser FormTreasureScene", "theme/form React activities"],
        grade_fit={"lower_primary": "不做抽象曲式排序。", "middle_primary": "听主题是否回来。", "upper_primary": "ABA、回旋和对比排序。"},
        pedagogy_notes=["曲式必须绑定音频段落复听。", "图形只帮助看见结构，最终回到听觉依据。"],
    ),
    "theme_return_core": _spec(
        "theme_return_core",
        "主题再现",
        primary_competency="审美感知",
        student_practices=["listen", "move", "explain"],
        music_elements=["主题", "重复", "再现"],
        teaching_stages=["欣赏复听"],
        supported_materials=["theme_windows", "audio_clip", "action_set"],
        core_loop=["listen_theme", "wait", "move_on_return", "explain"],
        required_components=["audio_player", "body_action_cards", "form_card_timeline"],
        required_rules=["theme_return_window_rule"],
        required_teacher_controls=["playback_control_pack", "hint_visibility_pack", "reset_pack"],
        optional_assets=["body_action_card_pack", "form_shape_card_pack"],
        difficulty_controls=["show_theme_hint", "window_tolerance", "theme_count"],
        applicable_activity_ids=["theme_return_action", "form_ordering", "picture_listening_intro"],
        implementation_status=ACTIVITY_READY,
        evidence=["主题再现动作 React 活动页", "form timeline component"],
        grade_fit={"lower_primary": "听到主题做动作。", "middle_primary": "举主题卡或动作确认。", "upper_primary": "说明主题变化或再现依据。"},
        pedagogy_notes=["主题再现活动不是普通反应游戏。", "动作必须绑定主题回来的听觉证据。"],
    ),
    "lyrics_rhythm_core": _spec(
        "lyrics_rhythm_core",
        "歌词节奏工坊",
        primary_competency="艺术表现",
        student_practices=["read", "tap", "sing"],
        music_elements=["歌词", "节奏", "乐句"],
        teaching_stages=["学唱", "节奏朗读"],
        supported_materials=["lyrics_phrase", "rhythm_pattern", "meter"],
        core_loop=["listen_beat", "read_lyrics", "tap_rhythm", "sing"],
        required_components=["lyrics_strip", "meter_track", "rhythm_card_bank"],
        required_rules=["rhythm_pattern_order_rule", "bar_length_rule"],
        required_teacher_controls=["tempo_control_pack", "hint_visibility_pack", "teacher_confirm_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["phrase_count", "hide_words", "bpm"],
        applicable_activity_ids=["lyrics_rhythm_reading", "lyrics_rhythm_practice", "phrase_loop_singing"],
        implementation_status=ACTIVITY_READY,
        evidence=["歌词节奏 React 活动页", "material binder lyrics_rhythm_binder"],
        grade_fit={"lower_primary": "按拍读短句。", "middle_primary": "读、拍、唱三步。", "upper_primary": "可加入重音和乐句处理。"},
        pedagogy_notes=["歌词节奏要回到演唱。", "不能只做文字填空或读字游戏。"],
    ),
    "phrase_singing_core": _spec(
        "phrase_singing_core",
        "乐句跟唱闯关",
        primary_competency="艺术表现",
        student_practices=["listen", "sing", "evaluate"],
        music_elements=["乐句", "旋律", "歌词"],
        teaching_stages=["学唱", "巩固"],
        supported_materials=["lyrics_phrase", "melody_phrase", "audio_clip"],
        core_loop=["listen_phrase", "sing_back", "teacher_confirm", "next_phrase"],
        required_components=["audio_player", "lyrics_strip", "teacher_control_bar"],
        required_rules=["singback_teacher_confirm_rule"],
        required_teacher_controls=["phrase_loop_pack", "teacher_confirm_pack", "tempo_control_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["phrase_length", "show_pitch_hint", "repeat_count"],
        applicable_activity_ids=["phrase_singing_practice", "phrase_loop_singing", "solfege_echo_singing"],
        implementation_status=ACTIVITY_READY,
        evidence=["乐句学唱 React 活动页", "phrase loop controls"],
        grade_fit={"lower_primary": "只做听一句唱一句，少文字，教师确认。", "middle_primary": "加入歌词节奏和难点句循环。", "upper_primary": "加入简单乐谱提示和自评。"},
        pedagogy_notes=["先听整体，再分句模唱。", "游戏反馈不能代替教师对声音状态的判断。"],
    ),
    "composition_puzzle_core": _spec(
        "composition_puzzle_core",
        "拼图创编",
        primary_competency="创意实践",
        student_practices=["create", "play", "listen", "revise"],
        music_elements=["节奏", "旋律", "小节"],
        teaching_stages=["创编"],
        supported_materials=["meter", "card_pool", "allowed_notes"],
        core_loop=["drag_cards", "validate_bar", "playback", "revise"],
        required_components=["rhythm_card_bank", "virtual_xylophone", "meter_track"],
        required_rules=["creation_bar_fit_rule", "pentatonic_constraint_rule"],
        required_teacher_controls=["teacher_confirm_pack", "reset_pack", "result_review_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["bar_count", "allowed_notes", "card_count"],
        applicable_activity_ids=["xylophone_creation", "body_percussion_builder", "graphic_score_create"],
        implementation_status=RUNTIME_READY,
        evidence=["game_template_registry", "Phaser CompositionPuzzleScene", "五声音条琴创编页"],
        grade_fit={"lower_primary": "不做复杂拼图创编。", "middle_primary": "短小节节奏替换。", "upper_primary": "五声旋律和节奏结构创编。"},
        pedagogy_notes=["创编必须有小节和音级限制。", "必须能回放、修改和说明意图。"],
    ),
    "orff_ensemble_core": _spec(
        "orff_ensemble_core",
        "奥尔夫合奏",
        primary_competency="艺术表现",
        student_practices=["play", "listen", "cooperate", "perform"],
        music_elements=["节奏声部", "进入", "力度"],
        teaching_stages=["器乐", "合作展示"],
        supported_materials=["group_tasks", "ensemble_parts", "meter"],
        core_loop=["assign_parts", "listen_cue", "enter_on_cue", "review"],
        required_components=["group_task_board", "meter_track", "ensemble_controller"],
        required_rules=["ensemble_entry_rule", "rubric_score_rule"],
        required_teacher_controls=["mute_solo_pack", "group_rotation_pack", "tempo_control_pack"],
        optional_assets=["generated_playable_instrument_pack", "reward_badge_pack"],
        difficulty_controls=["part_count", "bpm", "cue_visibility"],
        applicable_activity_ids=["orff_percussion_ensemble", "classroom_band_roles"],
        implementation_status=ACTIVITY_READY,
        evidence=["奥尔夫合奏 React 活动页", "进入判定和小组记录"],
        grade_fit={"lower_primary": "简单固定节奏声部。", "middle_primary": "轮奏、合奏和进入。", "upper_primary": "声部配合、独奏/合奏和评价。"},
        pedagogy_notes=["合奏重点是倾听、进入和声部配合。", "不能变成多人同时乱敲。"],
    ),
    "group_relay_core": _spec(
        "group_relay_core",
        "小组接力",
        primary_competency="艺术表现",
        student_practices=["perform", "cooperate", "evaluate"],
        music_elements=["合作", "展示", "评价"],
        teaching_stages=["展示", "合作"],
        supported_materials=["group_tasks", "rubric", "classroom_sequence"],
        core_loop=["group_turn", "perform_task", "peer_feedback", "next_group"],
        required_components=["group_task_board", "rubric_panel", "teacher_control_bar"],
        required_rules=["group_turn_rule", "rubric_score_rule"],
        required_teacher_controls=["group_rotation_pack", "classroom_timer_pack", "result_review_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["group_count", "task_count", "timer"],
        applicable_activity_ids=["group_relay_performance", "show_and_peer_feedback"],
        implementation_status=ACTIVITY_READY,
        evidence=["小组接力 React 活动页", "同伴评价 React 活动页"],
        grade_fit={"lower_primary": "短任务轮换。", "middle_primary": "小组展示和同伴一句反馈。", "upper_primary": "评价量规和改进建议。"},
        pedagogy_notes=["接力任务必须是音乐表现任务。", "评价不以排名为主，要说音乐依据。"],
    ),
    "exit_ticket_core": _spec(
        "exit_ticket_core",
        "课堂出口票",
        primary_competency="审美感知",
        secondary_competency="评价",
        student_practices=["choose", "explain", "evaluate"],
        music_elements=["本课核心音乐要素", "评价", "依据"],
        teaching_stages=["收尾", "复习"],
        supported_materials=["music_focus", "evidence_terms", "assessment_criteria"],
        core_loop=["choose_focus", "choose_evidence", "write_reason", "export"],
        required_components=["evidence_word_cards", "rubric_panel", "teacher_control_bar"],
        required_rules=["rubric_score_rule", "mood_choice_rule"],
        required_teacher_controls=["result_review_pack", "teacher_confirm_pack", "reset_pack"],
        optional_assets=["reward_badge_pack"],
        difficulty_controls=["evidence_count", "prompt_visibility", "teacher_review"],
        applicable_activity_ids=["exit_ticket_review", "listen_choose_explain", "show_and_peer_feedback"],
        implementation_status=ACTIVITY_READY,
        evidence=["课堂出口票 React 活动页", "JSON 导出和复盘建议"],
        grade_fit={"lower_primary": "选一个感受或动作。", "middle_primary": "选证据词并说一句理由。", "upper_primary": "写出音乐依据和下节课建议。"},
        pedagogy_notes=["出口票必须围绕本课音乐要素。", "不能只写喜欢或不喜欢。"],
    ),
}


def list_gameplay_template_specs() -> list[dict[str, Any]]:
    return [validate_gameplay_template_spec(spec) for spec in GAMEPLAY_TEMPLATE_CATALOG.values()]


def get_gameplay_template_spec(template_id: str) -> dict[str, Any]:
    spec = GAMEPLAY_TEMPLATE_CATALOG.get(str(template_id or ""))
    if not spec:
        raise ValueError(f"unknown gameplay template: {template_id}")
    return validate_gameplay_template_spec(spec)


def gameplay_template_specs_for_activity(activity_id: str) -> list[dict[str, Any]]:
    normalized = str(activity_id or "")
    return [
        spec
        for spec in list_gameplay_template_specs()
        if normalized in spec.get("applicable_activity_ids", [])
    ]


def validate_gameplay_template_spec(spec: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(spec, dict):
        raise ValueError("gameplay template spec must be a dict")
    missing = [
        field
        for field in REQUIRED_GAMEPLAY_TEMPLATE_FIELDS
        if field not in spec or spec.get(field) is None or spec.get(field) == ""
    ]
    if missing:
        raise ValueError(f"gameplay template spec missing fields: {', '.join(missing)}")
    if spec.get("version") != "gameplay_template_spec_v1":
        raise ValueError("gameplay template spec version must be gameplay_template_spec_v1")
    if spec.get("audience") != "primary_school":
        raise ValueError("gameplay template spec audience must be primary_school")
    if spec.get("implementation_status") not in {RUNTIME_READY, ACTIVITY_READY, SPEC_READY}:
        raise ValueError("gameplay template implementation_status is unsupported")
    for field in (
        "music_elements",
        "student_practices",
        "teaching_stages",
        "supported_materials",
        "core_loop",
        "required_components",
        "required_rules",
        "required_teacher_controls",
        "difficulty_controls",
        "quality_gates",
        "evidence",
        "applicable_activity_ids",
    ):
        if not isinstance(spec.get(field), list) or not spec[field]:
            raise ValueError(f"gameplay template {field} must be a non-empty list")
    alignment = spec.get("education_alignment")
    if not isinstance(alignment, dict):
        raise ValueError("gameplay template education_alignment must be a dict")
    for field in ("primary_competency", "student_practices", "music_elements", "teaching_stages", "grade_fit", "pedagogy_notes"):
        if not alignment.get(field):
            raise ValueError(f"gameplay template education_alignment missing {field}")
    if alignment["primary_competency"] != spec["primary_competency"]:
        raise ValueError("gameplay template primary competency mismatch")
    if not isinstance(alignment.get("grade_fit"), dict) or not alignment["grade_fit"]:
        raise ValueError("gameplay template grade_fit must be a non-empty dict")
    if not isinstance(alignment.get("pedagogy_notes"), list) or len(alignment["pedagogy_notes"]) < 2:
        raise ValueError("gameplay template pedagogy_notes must include at least two notes")
    return deepcopy(spec)
