from __future__ import annotations

from typing import Any

from app.services.activities.activity_spec import validate_activity_template_spec

# 保存系统支持的课堂活动类型，是“活动目录”

ACTIVITY_TEMPLATE_REGISTRY: dict[str, dict[str, Any]] = {
    "rhythm_warmup": {
        "version": "activity_template_spec_v1",
        "activity_id": "rhythm_warmup",
        "name": "节奏热身",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["导入", "节奏练习", "巩固"],
        "student_music_behaviors": ["listen", "tap", "move"],
        "required_material_entities": ["rhythm_pattern", "meter"],
        "toolkit": {
            "components": ["audio_player", "rhythm_card_bank", "meter_track", "tap_feedback", "teacher_control_bar"],
            "teaching_aids": ["rhythm_cards"],
            "virtual_instruments": ["rhythm_pad"],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "meter", "repeat_count", "grade_preset", "practice_mode", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust", "complete_rhythm_result_visible"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "tap", "move"],
            "music_elements": ["稳定拍", "节奏", "休止"],
            "teaching_stages": ["导入", "节奏练习", "巩固"],
            "grade_fit": {
                "lower_primary": "以听、拍、动建立稳定拍，少文字，强图形提示。",
                "middle_primary": "加入四分、八分、休止的节奏卡识别和模仿。",
                "upper_primary": "可隐藏提示，要求学生说出节奏疏密和休止位置。",
            },
            "pedagogy_notes": [
                "先听到稳定拍，再用身体和节奏垫表现。",
                "播放、谱面和判定必须共用同一套内部音头时间线。",
                "休止不是空白，要作为停住的音乐表现来反馈。",
                "网页给出敲击时间证据，动作质量、力度和音乐表现仍由教师观察。",
            ],
        },
    },
    "meter_body_movement": {
        "version": "activity_template_spec_v1",
        "activity_id": "meter_body_movement",
        "name": "强弱拍律动",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["导入", "律动", "学唱前体验"],
        "student_music_behaviors": ["listen", "move", "tap"],
        "required_material_entities": ["meter", "rhythm_pattern"],
        "toolkit": {
            "components": ["meter_track", "body_action_cards", "tap_feedback", "teacher_control_bar"],
            "teaching_aids": ["body_percussion_cards"],
            "virtual_instruments": ["virtual_hand_drum"],
            "game_templates": ["beat_guardian_core"],
        },
        "teacher_controls": ["tempo", "show_strong_beat", "hide_words", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "move", "tap"],
            "music_elements": ["节拍", "拍号", "强弱"],
            "teaching_stages": ["导入", "律动", "学唱前体验"],
            "grade_fit": {
                "lower_primary": "用大动作感受强弱，不要求抽象解释拍号。",
                "middle_primary": "能区分二拍子、三拍子的强弱规律，并用动作表现。",
            },
            "pedagogy_notes": ["强弱拍要先通过身体律动体验，再进入符号或游戏判定。", "低段反馈重点是是否跟上强拍，不做复杂术语讲解。"],
            "music_learning_path": {
                "experience": "学生先听二拍子或三拍子的稳定拍，感受强拍和弱拍。",
                "performance": "学生用大动作表现强拍，用轻动作或小动作表现弱拍。",
                "understanding": "学生能说出强弱规律和自己动作对应的拍点。",
                "transfer_or_creation": "学生把强弱拍动作迁移到歌曲导入或律动伴奏中。",
            },
        },
    },
    "strong_weak_beat_circle": {
        "version": "activity_template_spec_v1",
        "activity_id": "strong_weak_beat_circle",
        "name": "强弱拍圆圈",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["导入", "律动", "学唱前体验"],
        "student_music_behaviors": ["listen", "move", "tap"],
        "required_material_entities": ["meter", "rhythm_pattern"],
        "toolkit": {
            "components": ["meter_track", "body_action_cards", "tap_feedback", "teacher_control_bar"],
            "teaching_aids": ["body_percussion_cards"],
            "virtual_instruments": ["virtual_hand_drum"],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "show_strong_beat", "hide_words", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "move", "tap"],
            "music_elements": ["节拍", "拍号", "强弱"],
            "teaching_stages": ["导入", "律动", "学唱前体验"],
            "grade_fit": {
                "lower_primary": "围圈做强拍大动作、弱拍小动作，先身体体验，不要求抽象解释拍号。",
                "middle_primary": "能区分二拍子、三拍子的强弱规律，并用围圈动作保持稳定拍。",
            },
            "pedagogy_notes": [
                "围圈强弱拍活动必须先听音乐中的稳定拍和强弱关系，再用身体动作表现。",
                "强拍动作要清楚，弱拍动作要轻但不断拍，避免只抢第 1 拍。",
            ],
        },
    },
    "steady_beat_walk": {
        "version": "activity_template_spec_v1",
        "activity_id": "steady_beat_walk",
        "name": "稳定拍行走",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["导入", "律动", "节奏练习"],
        "student_music_behaviors": ["listen", "move", "tap", "perform"],
        "required_material_entities": ["rhythm_pattern", "meter"],
        "toolkit": {
            "components": ["audio_player", "meter_track", "tap_feedback", "body_action_cards", "teacher_control_bar"],
            "teaching_aids": ["body_percussion_cards", "rhythm_cards"],
            "virtual_instruments": ["rhythm_pad"],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "show_beat", "hide_hint", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "move", "tap", "perform"],
            "music_elements": ["稳定拍", "节奏", "休止"],
            "teaching_stages": ["导入", "律动", "节奏练习"],
            "grade_fit": {
                "lower_primary": "先听稳定拍，再用走一步、拍手、停住等大动作建立稳定拍，不要求术语解释。",
                "middle_primary": "可加入节奏卡和休止符停住提示，让学生说出哪些拍要走、哪些拍要停。",
            },
            "pedagogy_notes": [
                "稳定拍行走必须先听稳定拍，再进入走、拍、停的身体体验。",
                "休止要表现为停住，不是漏做；教师观察全班是否一起落在拍点上。",
            ],
        },
    },
    "phrase_singing_practice": {
        "version": "activity_template_spec_v1",
        "activity_id": "phrase_singing_practice",
        "name": "乐句学唱",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["学唱", "巩固"],
        "student_music_behaviors": ["listen", "sing", "explain"],
        "required_material_entities": ["lyrics_phrase", "melody_phrase", "audio_clip"],
        "toolkit": {
            "components": ["audio_player", "lyrics_strip", "teacher_control_bar"],
            "teaching_aids": ["lyrics_rhythm_strip"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["phrase_loop", "tempo", "show_pitch_hint", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "student_practices": ["listen", "sing", "explain"],
            "music_elements": ["乐句", "旋律", "歌词"],
            "teaching_stages": ["学唱", "巩固"],
            "grade_fit": {
                "lower_primary": "听一句唱一句，突出歌词和旋律模仿，教师确认优先。",
                "middle_primary": "加入难点乐句循环和歌词节奏提示。",
                "upper_primary": "加入乐句处理、呼吸位置和简短演唱评价。",
            },
            "pedagogy_notes": ["学唱要先整体感受，再分句模唱和难点句重练。", "儿童歌唱表现不优先自动评分，保留教师确认和提示。"],
        },
    },
    "phrase_loop_singing": {
        "version": "activity_template_spec_v1",
        "activity_id": "phrase_loop_singing",
        "name": "分句循环学唱",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["学唱", "巩固"],
        "student_music_behaviors": ["listen", "sing", "explain"],
        "required_material_entities": ["lyrics_phrase", "melody_phrase", "audio_clip"],
        "toolkit": {
            "components": ["audio_player", "lyrics_strip", "teacher_control_bar"],
            "teaching_aids": ["lyrics_rhythm_strip"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["phrase_loop", "tempo", "show_pitch_hint", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "student_practices": ["listen", "sing", "explain"],
            "music_elements": ["乐句", "旋律", "歌词"],
            "teaching_stages": ["学唱", "巩固"],
            "grade_fit": {
                "lower_primary": "只做听一句唱一句，少文字，教师确认后进入下一句。",
                "middle_primary": "按乐句循环听唱，能关注歌词、乐句记忆和自然声音。",
                "upper_primary": "可隐藏部分提示，要求学生说出旋律走向或演唱处理依据。",
            },
            "pedagogy_notes": [
                "听一句、唱一句、循环当前句、教师确认，是小学歌曲分句学唱的核心流程。",
                "先整体听歌曲，再进入分句循环，不能把唱歌课变成只点按钮得分。",
            ],
        },
    },
    "lyrics_rhythm_practice": {
        "version": "activity_template_spec_v1",
        "activity_id": "lyrics_rhythm_practice",
        "name": "歌词节奏",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["学唱前准备", "节奏练习", "学唱"],
        "student_music_behaviors": ["listen", "read", "tap", "sing"],
        "required_material_entities": ["lyrics_phrase", "rhythm_pattern", "meter"],
        "toolkit": {
            "components": ["audio_player", "lyrics_strip", "rhythm_card_bank", "meter_track", "teacher_control_bar"],
            "teaching_aids": ["lyrics_rhythm_strip", "rhythm_cards"],
            "virtual_instruments": ["rhythm_pad"],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "show_beat", "hide_words", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "read", "tap", "sing"],
            "music_elements": ["歌词", "节奏", "节拍"],
            "teaching_stages": ["学唱前准备", "节奏练习", "学唱"],
            "grade_fit": {
                "lower_primary": "用拍手、点读和大字歌词建立歌词与稳定拍的关系。",
                "middle_primary": "加入四分、八分、休止等节奏卡，能按节拍朗读歌词后再唱。",
            },
            "pedagogy_notes": [
                "歌词节奏要先按稳定拍读，再拍节奏，最后回到歌曲演唱。",
                "低段不做复杂节奏术语考试，重点观察歌词是否落在拍点上。",
            ],
        },
    },
    "lyrics_rhythm_reading": {
        "version": "activity_template_spec_v1",
        "activity_id": "lyrics_rhythm_reading",
        "name": "歌词节奏朗读",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["学唱前准备", "节奏练习", "学唱"],
        "student_music_behaviors": ["listen", "read", "tap", "sing"],
        "required_material_entities": ["lyrics_phrase", "rhythm_pattern", "meter"],
        "toolkit": {
            "components": ["audio_player", "lyrics_strip", "rhythm_card_bank", "meter_track", "teacher_control_bar"],
            "teaching_aids": ["lyrics_rhythm_strip", "rhythm_cards"],
            "virtual_instruments": ["rhythm_pad"],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "show_beat", "hide_words", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "read", "tap", "sing"],
            "music_elements": ["歌词", "节奏", "节拍"],
            "teaching_stages": ["学唱前准备", "节奏练习", "学唱"],
            "grade_fit": {
                "lower_primary": "用大字歌词、拍手和点读建立歌词字音与稳定拍的关系。",
                "middle_primary": "能按节拍朗读歌词，再用节奏卡或身体动作拍出歌词节奏。",
            },
            "pedagogy_notes": [
                "先按稳定拍读歌词，再拍出歌词节奏，最后回到歌曲演唱。",
                "歌词节奏朗读不是文字填空，要让学生听、读、拍、唱形成连接。",
            ],
        },
    },
    "rhythm_question_answer": {
        "version": "activity_template_spec_v1",
        "activity_id": "rhythm_question_answer",
        "name": "节奏问答",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["节奏练习", "创编", "合作"],
        "student_music_behaviors": ["listen", "tap", "create", "perform", "explain"],
        "required_material_entities": ["rhythm_pattern", "meter"],
        "toolkit": {
            "components": ["audio_player", "rhythm_card_bank", "tap_feedback", "teacher_control_bar"],
            "teaching_aids": ["rhythm_cards"],
            "virtual_instruments": ["rhythm_pad"],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "show_beat", "hide_hint", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "创意实践",
            "student_practices": ["listen", "tap", "create", "perform", "explain"],
            "music_elements": ["节奏", "节拍", "创编结构"],
            "teaching_stages": ["节奏练习", "创编", "合作"],
            "grade_fit": {
                "middle_primary": "先听教师节奏问句，再用节奏卡或节奏垫回拍一个小节答句。",
                "upper_primary": "可要求答句保持同拍号小节完整，并说出和问句的相同或变化。",
            },
            "pedagogy_notes": [
                "节奏问答必须先听问句，再回拍答句，不能直接随机拼卡。",
                "答句要符合拍号和小节长度，教师可让小组轮流接答。",
            ],
        },
    },
    "solfege_sorting": {
        "version": "activity_template_spec_v1",
        "activity_id": "solfege_sorting",
        "name": "唱名排序",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["音高练习", "识谱前准备"],
        "student_music_behaviors": ["listen", "arrange", "sing"],
        "required_material_entities": ["solfege_set", "pitch_motion"],
        "toolkit": {
            "components": ["audio_player", "solfege_card_bank", "teacher_control_bar"],
            "teaching_aids": ["solfege_cards", "pitch_ladder_board"],
            "virtual_instruments": ["virtual_xylophone"],
            "game_templates": ["pitch_ladder_core", "solfege_target_core"],
        },
        "teacher_controls": ["show_solfege", "hide_solfege", "limit_pitch_count", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "arrange", "sing"],
            "music_elements": ["音高", "唱名", "旋律"],
            "teaching_stages": ["音高练习", "识谱前准备"],
            "grade_fit": {
                "middle_primary": "用 do/re/mi/sol/la 建立唱名和音高方向感。",
                "upper_primary": "可加入简谱或旋律短句排序，但不进入复杂视唱评分。",
            },
            "pedagogy_notes": ["唱名排序要从听辨和模唱出发，而不是只做符号排列。", "音高活动要限制音级数量，避免一次给出过多选项。"],
        },
    },
    "solfege_echo_singing": {
        "version": "activity_template_spec_v1",
        "activity_id": "solfege_echo_singing",
        "name": "唱名回声",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["音高练习", "学唱前准备"],
        "student_music_behaviors": ["listen", "sing", "explain"],
        "required_material_entities": ["solfege_set", "pitch_motion", "audio_clip"],
        "toolkit": {
            "components": ["audio_player", "solfege_card_bank", "teacher_control_bar"],
            "teaching_aids": ["solfege_cards", "pitch_ladder_board"],
            "virtual_instruments": ["virtual_xylophone"],
            "game_templates": [],
        },
        "teacher_controls": ["show_solfege", "hide_solfege", "limit_pitch_count", "tempo", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "sing", "explain"],
            "music_elements": ["音高", "唱名", "旋律"],
            "teaching_stages": ["音高练习", "学唱前准备"],
            "grade_fit": {
                "middle_primary": "教师唱或播放短唱名组，学生用回声方式模唱，限制在 do/re/mi/sol/la 内。",
                "upper_primary": "可加入上行、下行、跳进等旋律走向说明，再回到歌曲或简谱片段。",
            },
            "pedagogy_notes": [
                "教师唱一句，学生先听后回声模唱，重点是音高和唱名对应，不是只拖拽排序。",
                "回声模唱需要保留教师确认，儿童歌唱不做纯自动评分。",
            ],
        },
    },
    "melody_contour_trace": {
        "version": "activity_template_spec_v1",
        "activity_id": "melody_contour_trace",
        "name": "旋律线描一描",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["学唱前准备", "欣赏", "巩固"],
        "student_music_behaviors": ["listen", "move", "sing", "explain"],
        "required_material_entities": ["pitch_motion", "melody_phrase", "audio_clip"],
        "toolkit": {
            "components": ["audio_player", "melody_contour_line", "teacher_control_bar"],
            "teaching_aids": ["melody_contour_board", "pitch_ladder_board"],
            "virtual_instruments": ["virtual_xylophone"],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "show_hint", "hide_hint", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "move", "sing", "explain"],
            "music_elements": ["旋律", "音高"],
            "teaching_stages": ["学唱前准备", "欣赏", "巩固"],
            "grade_fit": {
                "middle_primary": "先听短旋律，再用手势画出上行、下行或平稳，最后用唱名或哼唱回到声音。",
                "upper_primary": "可加入简短唱名提示、旋律线依据说明和听赏复听迁移。",
            },
            "pedagogy_notes": [
                "旋律线活动必须先听旋律，再用手势或线条跟踪音高走向。",
                "线条反馈要回到上行、下行、平稳和唱回，不做脱离声音的看图判断。",
            ],
        },
    },
    "simple_score_following": {
        "version": "activity_template_spec_v1",
        "activity_id": "simple_score_following",
        "name": "简谱跟读",
        "audience": "primary_school",
        "grade_bands": ["upper_primary"],
        "classroom_stage": ["识谱", "学唱前准备", "巩固"],
        "student_music_behaviors": ["listen", "read", "sing", "explain"],
        "required_material_entities": ["numbered_score", "rhythm_pattern", "audio_clip"],
        "toolkit": {
            "components": ["audio_player", "score_following_board", "teacher_control_bar"],
            "teaching_aids": ["simple_score_board", "solfege_cards", "rhythm_cards"],
            "virtual_instruments": ["virtual_xylophone"],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "tempo", "show_solfege", "hide_solfege", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "read", "sing", "explain"],
            "music_elements": ["识谱", "唱名", "节奏", "旋律"],
            "teaching_stages": ["识谱", "学唱前准备", "巩固"],
            "grade_fit": {
                "upper_primary": "先听音频和教师示范，再跟读简谱唱名与节奏，建立谱面和声音对应。",
            },
            "pedagogy_notes": [
                "简谱跟读要先听再读，不能变成脱离声音的符号考试。",
                "小学高段只做短句、唱名和节奏对应，视唱表现保留教师确认。",
            ],
        },
    },
    "picture_listening_intro": {
        "version": "activity_template_spec_v1",
        "activity_id": "picture_listening_intro",
        "name": "看图听赏导入",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["导入", "初听"],
        "student_music_behaviors": ["listen", "choose", "explain"],
        "required_material_entities": ["audio_clip", "expression_trait"],
        "toolkit": {
            "components": ["compare_player", "picture_prompt_cards", "teacher_control_bar"],
            "teaching_aids": ["mood_picture_cards"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "hide_words", "show_reason_prompt", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "student_practices": ["listen", "choose", "explain"],
            "music_elements": ["情绪", "速度", "力度"],
            "teaching_stages": ["导入", "初听"],
            "grade_fit": {
                "lower_primary": "用图片表达初听感受，鼓励用自己的话说理由。",
                "middle_primary": "加入速度、力度等音乐词作为听赏证据。",
            },
            "pedagogy_notes": ["欣赏导入必须先听音乐，再选择图片或词语。", "选择结果不是终点，要引导学生说出听到的音乐依据。"],
        },
    },
    "listen_choose_explain": {
        "version": "activity_template_spec_v1",
        "activity_id": "listen_choose_explain",
        "name": "听一听选一选",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["初听", "欣赏", "复听"],
        "student_music_behaviors": ["listen", "choose", "explain"],
        "required_material_entities": ["audio_clip", "expression_trait"],
        "toolkit": {
            "components": ["compare_player", "picture_prompt_cards", "teacher_control_bar"],
            "teaching_aids": ["mood_picture_cards"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "hide_words", "show_reason_prompt", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "student_practices": ["listen", "choose", "explain"],
            "music_elements": ["情绪", "速度", "力度"],
            "teaching_stages": ["初听", "欣赏", "复听"],
            "grade_fit": {
                "lower_primary": "先完整听，再用情绪图卡表达感受，教师追问速度或力度依据。",
                "middle_primary": "在情绪选择后必须补一个速度、力度或旋律依据，并复听验证。",
            },
            "pedagogy_notes": [
                "听一听选一选不是看图猜答案，必须先完整听音乐。",
                "选择后要说出音乐依据，至少指向速度、力度、旋律或音色中的一个听觉线索。",
            ],
        },
    },
    "lesson_opening_hook": {
        "version": "activity_template_spec_v1",
        "activity_id": "lesson_opening_hook",
        "name": "课堂导入钩子",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["导入", "初听"],
        "student_music_behaviors": ["listen", "choose", "explain"],
        "required_material_entities": ["audio_clip", "lesson_topic", "expression_trait"],
        "toolkit": {
            "components": ["audio_player", "picture_prompt_cards", "teacher_control_bar"],
            "teaching_aids": ["mood_picture_cards"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "hide_words", "show_reason_prompt", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "secondary_competency": "艺术表现",
            "student_practices": ["listen", "choose", "explain"],
            "music_elements": ["情绪", "速度", "力度", "旋律"],
            "teaching_stages": ["导入", "初听"],
            "grade_fit": {
                "lower_primary": "先听 20 到 40 秒音乐片段，用图片或一句话说感受，不讲长概念。",
                "middle_primary": "在情绪或画面选择后补一个速度、力度、旋律等音乐依据。",
            },
            "pedagogy_notes": [
                "课堂导入要先让学生听到教材音乐或相关片段，再用图卡、问题和音乐词进入新课。",
                "导入钩子只负责唤起经验和建立听觉关注点，不能替代后续学唱、欣赏或节奏实践。",
            ],
        },
    },
    "theme_return_action": {
        "version": "activity_template_spec_v1",
        "activity_id": "theme_return_action",
        "name": "主题再现动作",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["欣赏", "复听"],
        "student_music_behaviors": ["listen", "move", "explain"],
        "required_material_entities": ["audio_clip", "theme_windows"],
        "toolkit": {
            "components": ["audio_player", "theme_return_timeline", "movement_action_cards", "teacher_control_bar"],
            "teaching_aids": ["theme_action_cards"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "replay_section", "show_reason_prompt", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "student_practices": ["listen", "move", "explain"],
            "music_elements": ["主题", "重复", "再现"],
            "teaching_stages": ["欣赏", "复听"],
            "grade_fit": {
                "middle_primary": "用动作回应主题再次出现，先建立听觉识别。",
                "upper_primary": "在动作回应后说出旋律、节奏或力度上的再现依据。",
            },
            "pedagogy_notes": [
                "主题再现动作必须先听主题，再复听完整或片段，不能看时间提示猜答案。",
                "动作只是外显反应，最终要回到旋律相同、节奏相似等音乐依据。",
            ],
        },
    },
    "graphic_score_create": {
        "version": "activity_template_spec_v1",
        "activity_id": "graphic_score_create",
        "name": "图形谱创编",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["创编", "巩固", "展示"],
        "student_music_behaviors": ["create", "listen", "revise", "explain"],
        "required_material_entities": ["graphic_symbol_meanings", "meter"],
        "toolkit": {
            "components": ["audio_player", "graphic_score_canvas", "teacher_control_bar"],
            "teaching_aids": ["graphic_score_board"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "show_reason_prompt", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "创意实践",
            "secondary_competency": "审美感知",
            "student_practices": ["create", "listen", "revise", "explain"],
            "music_elements": ["图形谱", "音高", "力度", "节奏"],
            "teaching_stages": ["创编", "巩固", "展示"],
            "grade_fit": {
                "middle_primary": "用点、线、块建立高低、长短、强弱和顺序的直观联系。",
                "upper_primary": "能在回放后修改图形谱，并说明图形与音乐要素的对应。",
            },
            "pedagogy_notes": [
                "图形谱创编要先明确图形含义，再按顺序播放验证，不能只是自由画画。",
                "教师观察学生能否把图形和高低、长短、强弱等听觉经验连接起来。",
            ],
        },
    },
    "instrument_timbre_match": {
        "version": "activity_template_spec_v1",
        "activity_id": "instrument_timbre_match",
        "name": "音色匹配",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["欣赏", "复听", "巩固"],
        "student_music_behaviors": ["listen", "match", "explain"],
        "required_material_entities": ["timbre_set", "instrument_pool", "audio_clip"],
        "toolkit": {
            "components": ["compare_player", "instrument_card_grid", "teacher_control_bar"],
            "teaching_aids": ["instrument_evidence_cards"],
            "virtual_instruments": [],
            "game_templates": ["timbre_detective_core"],
        },
        "teacher_controls": ["replay", "show_family", "hide_picture", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "secondary_competency": "文化理解",
            "student_practices": ["listen", "match", "explain"],
            "music_elements": ["音色", "乐器"],
            "teaching_stages": ["欣赏", "复听", "巩固"],
            "grade_fit": {
                "middle_primary": "先听辨常见乐器音色，再匹配图片和音色词。",
                "upper_primary": "加入乐器家族、发声方式和简短证据表达。",
            },
            "pedagogy_notes": ["音色游戏必须先听声音，图片只能作为验证或辅助。", "要求学生选择音色证据词，避免只猜乐器名称。"],
        },
    },
    "form_ordering": {
        "version": "activity_template_spec_v1",
        "activity_id": "form_ordering",
        "name": "曲式排序",
        "audience": "primary_school",
        "grade_bands": ["upper_primary"],
        "classroom_stage": ["欣赏", "复听"],
        "student_music_behaviors": ["listen", "order", "explain"],
        "required_material_entities": ["form_structure", "audio_clip"],
        "toolkit": {
            "components": ["audio_player", "form_card_timeline", "teacher_control_bar"],
            "teaching_aids": ["form_cards"],
            "virtual_instruments": [],
            "game_templates": ["form_treasure_core"],
        },
        "teacher_controls": ["replay_section", "show_hint", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "student_practices": ["listen", "order", "explain"],
            "music_elements": ["曲式", "重复", "对比"],
            "teaching_stages": ["欣赏", "复听"],
            "grade_fit": {
                "upper_primary": "通过复听段落感受重复、对比和 ABA 等简单结构。",
            },
            "pedagogy_notes": ["曲式排序必须绑定音频段落，不能脱离听觉凭空排序。", "高段可以要求学生说出段落相同或不同的音乐依据。"],
        },
    },
    "instrument_family_sorting": {
        "version": "activity_template_spec_v1",
        "activity_id": "instrument_family_sorting",
        "name": "乐器家族分类",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["欣赏", "拓展", "文化理解"],
        "student_music_behaviors": ["listen", "classify", "explain"],
        "required_material_entities": ["instrument_pool", "instrument_family_set", "audio_clip"],
        "toolkit": {
            "components": ["compare_player", "instrument_card_grid", "teacher_control_bar"],
            "teaching_aids": ["instrument_evidence_cards"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["replay", "show_family", "hide_picture", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "文化理解",
            "secondary_competency": "审美感知",
            "student_practices": ["listen", "classify", "explain"],
            "music_elements": ["乐器家族", "音色", "发声方式"],
            "teaching_stages": ["欣赏", "拓展", "文化理解"],
            "grade_fit": {
                "middle_primary": "先听常见乐器音色，再按吹奏、拉弦、弹拨、打击等方式归类。",
                "upper_primary": "加入民族/西洋、发声方式和作品语境，要求说出分类依据。",
            },
            "pedagogy_notes": ["乐器分类必须先听声音，图片和名称只作为验证与文化拓展。", "文化理解要和音色、发声方式、作品语境联系，不能做成百科问答。"],
        },
    },
    "body_percussion_builder": {
        "version": "activity_template_spec_v1",
        "activity_id": "body_percussion_builder",
        "name": "身体打击编排",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary"],
        "classroom_stage": ["律动", "节奏练习", "展示"],
        "student_music_behaviors": ["move", "tap", "arrange", "create", "perform"],
        "required_material_entities": ["rhythm_pattern", "meter"],
        "toolkit": {
            "components": ["body_action_cards", "meter_track", "teacher_control_bar"],
            "teaching_aids": ["body_percussion_cards"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["tempo", "show_beat", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "创意实践",
            "secondary_competency": "艺术表现",
            "student_practices": ["move", "tap", "arrange", "create", "perform"],
            "music_elements": ["节奏", "节拍", "力度"],
            "teaching_stages": ["律动", "节奏练习", "展示"],
            "grade_fit": {
                "lower_primary": "用拍手、拍腿、跺脚等动作模仿和组合。",
                "middle_primary": "可按小节组织身体打击顺序，并进行小组展示。",
            },
            "pedagogy_notes": ["身体打击要服务节奏和节拍感，不是单纯动作游戏。", "编排时要校验总拍数，保证动作组合能落在音乐结构里。"],
        },
    },
    "xylophone_creation": {
        "version": "activity_template_spec_v1",
        "activity_id": "xylophone_creation",
        "name": "音条琴创编",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["创编", "展示"],
        "student_music_behaviors": ["play", "create", "listen", "revise"],
        "required_material_entities": ["solfege_set", "rhythm_pattern"],
        "toolkit": {
            "components": ["audio_player", "rhythm_card_bank", "teacher_control_bar"],
            "teaching_aids": ["rhythm_cards", "solfege_cards"],
            "virtual_instruments": ["virtual_xylophone", "pentatonic_grid"],
            "game_templates": ["composition_puzzle_core"],
        },
        "teacher_controls": ["limit_pitch_count", "tempo", "record", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "创意实践",
            "secondary_competency": "艺术表现",
            "student_practices": ["play", "create", "listen", "revise"],
            "music_elements": ["音高", "五声音阶", "节奏", "创编结构"],
            "teaching_stages": ["创编", "展示"],
            "grade_fit": {
                "middle_primary": "限制音级数量，用短节奏框架进行音条琴探索。",
                "upper_primary": "加入问答句、重复变化和创编回放修改。",
            },
            "pedagogy_notes": ["创编要有音级和节奏限制，让学生在可控范围内创造。", "必须支持回放和修改，形成听、创、改的学习闭环。"],
        },
    },
    "orff_percussion_ensemble": {
        "version": "activity_template_spec_v1",
        "activity_id": "orff_percussion_ensemble",
        "name": "奥尔夫打击乐合奏",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["器乐", "合作", "展示"],
        "student_music_behaviors": ["play", "listen", "cooperate", "perform"],
        "required_material_entities": ["rhythm_pattern", "classroom_group_task"],
        "toolkit": {
            "components": ["compare_player", "group_task_board", "meter_track", "teacher_control_bar"],
            "teaching_aids": ["group_mission_cards", "performance_rubric"],
            "virtual_instruments": ["virtual_hand_drum", "woodblock_claves", "shaker", "triangle_bell", "tambourine"],
            "ensemble_controllers": ["classroom_percussion_kit"],
            "game_templates": [],
        },
        "teacher_controls": ["mute_group", "solo_group", "tempo", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "创意实践",
            "student_practices": ["play", "listen", "cooperate", "perform"],
            "music_elements": ["节奏", "合作", "力度"],
            "teaching_stages": ["器乐", "合作", "展示"],
            "grade_fit": {
                "middle_primary": "用固定节奏声部进行轮奏和合奏。",
                "upper_primary": "加入声部进入、独奏/合奏对比和小组评价。",
            },
            "pedagogy_notes": ["合奏重点是倾听、进入和声部配合，不是同时乱敲。", "教师必须能静音、独奏和降速，保证课堂可控。"],
        },
    },
    "classroom_band_roles": {
        "version": "activity_template_spec_v1",
        "activity_id": "classroom_band_roles",
        "name": "小乐队分声部",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["器乐", "合作", "展示"],
        "student_music_behaviors": ["play", "listen", "cooperate", "perform"],
        "required_material_entities": ["rhythm_pattern", "classroom_group_task"],
        "toolkit": {
            "components": ["compare_player", "group_task_board", "meter_track", "teacher_control_bar"],
            "teaching_aids": ["group_mission_cards", "performance_rubric"],
            "virtual_instruments": ["virtual_hand_drum", "woodblock_claves", "shaker", "triangle_bell", "tambourine"],
            "ensemble_controllers": ["classroom_percussion_kit"],
            "game_templates": [],
        },
        "teacher_controls": ["mute_group", "solo_group", "tempo", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "创意实践",
            "student_practices": ["play", "listen", "cooperate", "perform"],
            "music_elements": ["节奏", "声部", "合作", "音色"],
            "teaching_stages": ["器乐", "合作", "展示"],
            "grade_fit": {
                "middle_primary": "先听手鼓、木鱼、沙锤等声部音色和固定节奏，再用小组任务卡分配声部。",
                "upper_primary": "加入声部进入、力度平衡、独奏/合奏对比和小组评价，要求说出听到的音色与进入依据。",
            },
            "pedagogy_notes": [
                "分声部不是平均分乐器，要让学生先听稳定拍和同伴声部，再按指挥进入。",
                "教师必须能调整声部、静音/独奏和降速，保证小乐队课堂可控。",
            ],
        },
    },
    "group_relay_performance": {
        "version": "activity_template_spec_v1",
        "activity_id": "group_relay_performance",
        "name": "小组接力展示",
        "audience": "primary_school",
        "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["合作", "展示", "评价"],
        "student_music_behaviors": ["cooperate", "perform", "assess"],
        "required_material_entities": ["classroom_group_task", "assessment_criteria"],
        "toolkit": {
            "components": ["group_task_board", "rubric_panel", "teacher_control_bar"],
            "teaching_aids": ["group_mission_cards", "performance_rubric"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["assign_group", "mark_done", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "艺术表现",
            "secondary_competency": "审美感知",
            "student_practices": ["cooperate", "perform", "assess"],
            "music_elements": ["合作", "评价"],
            "teaching_stages": ["合作", "展示", "评价"],
            "grade_fit": {
                "lower_primary": "以完成任务和大胆表现为主，评价维度少。",
                "middle_primary": "加入同伴倾听和节奏稳定等简单评价。",
                "upper_primary": "可加入合作、表现、音乐依据等评价维度。",
            },
            "pedagogy_notes": ["小组接力要围绕具体音乐任务，不能只做轮流点击。", "评价应强调音乐表现和合作倾听，不以排名为唯一目标。"],
        },
    },
    "show_and_peer_feedback": {
        "version": "activity_template_spec_v1",
        "activity_id": "show_and_peer_feedback",
        "name": "展示与同伴评价",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["展示", "评价", "巩固"],
        "student_music_behaviors": ["listen", "perform", "assess", "explain"],
        "required_material_entities": ["classroom_group_task", "assessment_criteria"],
        "toolkit": {
            "components": ["group_task_board", "rubric_panel", "teacher_control_bar"],
            "teaching_aids": ["group_mission_cards", "performance_rubric"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["assign_group", "show_reason_prompt", "save", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "secondary_competency": "艺术表现",
            "student_practices": ["listen", "perform", "assess", "explain"],
            "music_elements": ["评价", "合作"],
            "teaching_stages": ["展示", "评价", "巩固"],
            "grade_fit": {
                "middle_primary": "同伴评价用短句和少量维度，先听展示，再选择一个音乐依据。",
                "upper_primary": "能围绕节奏、音准、力度、进入、合作倾听等维度给出具体建议。",
            },
            "pedagogy_notes": [
                "展示评价必须先听或观看同伴音乐表现，再选择评价维度。",
                "同伴建议要指向具体音乐依据，不能只说好听、喜欢或排名。",
            ],
        },
    },
    "exit_ticket_review": {
        "version": "activity_template_spec_v1",
        "activity_id": "exit_ticket_review",
        "name": "课堂出口票",
        "audience": "primary_school",
        "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["复习", "评价"],
        "student_music_behaviors": ["choose", "explain", "assess"],
        "required_material_entities": ["assessment_criteria", "music_focus"],
        "toolkit": {
            "components": ["rubric_panel", "teacher_control_bar"],
            "teaching_aids": ["performance_rubric"],
            "virtual_instruments": [],
            "game_templates": [],
        },
        "teacher_controls": ["show_answer", "save", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {
            "primary_competency": "审美感知",
            "student_practices": ["choose", "explain", "assess"],
            "music_elements": ["评价"],
            "teaching_stages": ["复习", "评价"],
            "grade_fit": {
                "middle_primary": "用选择和一句话理由回顾本课音乐要素。",
                "upper_primary": "要求学生用音乐词或证据说明自己的判断。",
            },
            "pedagogy_notes": ["出口票要回到本课音乐目标，不做泛泛情绪打卡。", "记录结果用于教师判断下一步复习或拓展。"],
        },
    },
}


ACTIVITY_TEMPLATE_REGISTRY.update({
    "song_audio_workbench_activity": {
        "version": "activity_template_spec_v1", "activity_id": "song_audio_workbench_activity", "name": "音乐要素控制器",
        "audience": "primary_school", "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["备课", "导入", "学唱", "巩固"], "student_music_behaviors": ["listen", "sing", "explain"],
        "required_material_entities": ["audio_clip"],
        "toolkit": {"components": ["song_audio_workbench", "teacher_control_bar"], "teaching_aids": [], "virtual_instruments": [], "game_templates": []},
        "teacher_controls": ["upload", "tonic", "mode", "tempo", "rhythm_density", "instrument", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {"primary_competency": "审美感知", "secondary_competency": "艺术表现", "student_practices": ["listen", "sing", "explain"], "music_elements": ["音高", "旋律", "速度", "音色", "对比"], "teaching_stages": ["备课", "导入", "学唱", "巩固"], "grade_fit": {"lower_primary": "教师限定一个明显要素进行前后对比。", "middle_primary": "比较速度、节奏密度和常见音色变化。", "upper_primary": "加入主音、调式及多要素控制实验。"}, "pedagogy_notes": ["教师指定歌曲优先。", "每次突出一个主要变化要素。", "素材版权、学生音域和作品风格必须由教师确认。"]},
    },
    "score_audio_sync_practice": {
        "version": "activity_template_spec_v1", "activity_id": "score_audio_sync_practice", "name": "谱面与声音同步练习",
        "audience": "primary_school", "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["识谱", "学唱", "巩固"], "student_music_behaviors": ["listen", "read", "sing"],
        "required_material_entities": ["melody_phrase", "audio_clip"],
        "toolkit": {"components": ["score_audio_sync_player", "teacher_control_bar"], "teaching_aids": ["simple_score_board"], "virtual_instruments": [], "game_templates": []},
        "teacher_controls": ["score_view", "play", "seek", "loop", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {"primary_competency": "艺术表现", "secondary_competency": "审美感知", "student_practices": ["listen", "read", "sing"], "music_elements": ["识谱", "旋律", "节奏"], "teaching_stages": ["识谱", "学唱", "巩固"], "grade_fit": {"middle_primary": "以简谱和短乐句跟随为主。", "upper_primary": "可切换五线谱并进行小节循环。"}, "pedagogy_notes": ["谱面、光标和声音必须同源。", "识别草稿须教师确认。"]},
    },
    "ear_training_practice": {
        "version": "activity_template_spec_v1", "activity_id": "ear_training_practice", "name": "视唱练耳训练",
        "audience": "primary_school", "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["音高练习", "节奏练习", "识谱", "巩固"], "student_music_behaviors": ["listen", "choose", "tap", "sing", "explain"],
        "required_material_entities": ["solfege_set", "rhythm_pattern"],
        "toolkit": {"components": ["ear_training_engine", "teacher_control_bar"], "teaching_aids": ["solfege_cards", "rhythm_cards"], "virtual_instruments": ["simple_keyboard"], "game_templates": []},
        "teacher_controls": ["question_type", "pitch_range", "solfege_system", "random_policy", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {"primary_competency": "审美感知", "secondary_competency": "艺术表现", "student_practices": ["listen", "choose", "tap", "sing", "explain"], "music_elements": ["音高", "唱名", "节奏", "旋律"], "teaching_stages": ["音高练习", "节奏练习", "识谱", "巩固"], "grade_fit": {"lower_primary": "少量音级和听后模仿。", "middle_primary": "加入音程、节奏与短旋律。", "upper_primary": "加入主音感、调式和视唱。"}, "pedagogy_notes": ["随机出题必须由教师允许。", "真实演唱由教师确认。"]},
    },
    "vocal_choir_training_activity": {
        "version": "activity_template_spec_v1", "activity_id": "vocal_choir_training_activity", "name": "合唱与嗓音训练",
        "audience": "primary_school", "grade_bands": ["lower_primary", "middle_primary", "upper_primary"],
        "classroom_stage": ["发声准备", "学唱", "合唱", "巩固"], "student_music_behaviors": ["listen", "move", "sing", "revise"],
        "required_material_entities": ["melody_phrase", "audio_clip"],
        "toolkit": {"components": ["vocal_choir_training", "teacher_control_bar"], "teaching_aids": [], "virtual_instruments": ["simple_keyboard"], "game_templates": []},
        "teacher_controls": ["grade_preset", "range", "loop", "record", "confirm", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {"primary_competency": "艺术表现", "secondary_competency": "审美感知", "student_practices": ["listen", "move", "sing", "revise"], "music_elements": ["音高", "乐句", "声部", "合作"], "teaching_stages": ["发声准备", "学唱", "合唱", "巩固"], "grade_fit": {"lower_primary": "短时、自然、轻声模唱。", "middle_primary": "加入乐句呼吸和轮唱。", "upper_primary": "加入儿童二声部与自我回听。"}, "pedagogy_notes": ["禁止喊唱和强行扩展音域。", "音色、气息、咬字和融合由教师判断。"]},
    },
    "ensemble_conductor_rehearsal": {
        "version": "activity_template_spec_v1", "activity_id": "ensemble_conductor_rehearsal", "name": "多声部排练与指挥",
        "audience": "primary_school", "grade_bands": ["middle_primary", "upper_primary"],
        "classroom_stage": ["合奏", "合唱", "排练", "展示"], "student_music_behaviors": ["listen", "play", "perform", "cooperate", "assess"],
        "required_material_entities": ["classroom_group_task", "audio_clip"],
        "toolkit": {"components": ["ensemble_conductor", "teacher_control_bar"], "teaching_aids": ["group_mission_cards"], "virtual_instruments": [], "game_templates": []},
        "teacher_controls": ["mute", "solo", "volume", "loop", "entry_cue", "reset"],
        "acceptance": ["material_bound", "student_can_operate", "teacher_can_adjust"],
        "education_alignment": {"primary_competency": "艺术表现", "secondary_competency": "审美感知", "student_practices": ["listen", "play", "perform", "cooperate", "assess"], "music_elements": ["声部", "节奏", "合作", "力度"], "teaching_stages": ["合奏", "合唱", "排练", "展示"], "grade_fit": {"middle_primary": "轮唱、固定节奏声部和简单进入。", "upper_primary": "儿童二声部和课堂乐队分轨排练。"}, "pedagogy_notes": ["预备拍与正式音乐分离。", "声部平衡和合作聆听由教师判断。"]},
    },
})

# 列出活动；
def list_activity_templates() -> list[dict[str, Any]]:
    return [validate_activity_template_spec(spec) for spec in ACTIVITY_TEMPLATE_REGISTRY.values()]

# 按 ID 查询活动
def get_activity_template(activity_id: str) -> dict[str, Any]:
    spec = ACTIVITY_TEMPLATE_REGISTRY.get(str(activity_id or ""))
    if not spec:
        raise ValueError(f"unknown activity template: {activity_id}")
    return validate_activity_template_spec(spec)
