from __future__ import annotations

from copy import deepcopy
from typing import Any


PLAY_MODE_STRUCTURES: dict[str, dict[str, str]] = {
    "race": {
        "playfield_composition": "赛道、进度、冲刺终点",
        "camera_profile": "side_race_push",
        "hud_model": "speed_combo_finish",
    },
    "gate": {
        "playfield_composition": "中央护盾、呼吸节拍环、弱拍怪物行进路径",
        "camera_profile": "front_shield_arena",
        "hud_model": "energy_combo_target",
    },
    "station": {
        "playfield_composition": "轨道、站台、准点进站",
        "camera_profile": "platform_timing_lane",
        "hud_model": "arrival_combo_clock",
    },
    "spotlight": {
        "playfield_composition": "舞台、追光、演员站位",
        "camera_profile": "stage_spotlight_sweep",
        "hud_model": "spotlight_combo_cue",
    },
    "orbit": {
        "playfield_composition": "星轨、轨道窗口、星球稳定度",
        "camera_profile": "orbital_focus_ring",
        "hud_model": "orbit_energy_window",
    },
    "radio": {
        "playfield_composition": "电波轨、传呼按钮、飞船对接窗口",
        "camera_profile": "radio_console_closeup",
        "hud_model": "demo_record_accuracy",
    },
    "cave": {
        "playfield_composition": "山洞回声、波纹反射、记忆轨",
        "camera_profile": "echo_cave_depth",
        "hud_model": "memory_echo_rings",
    },
    "signal": {
        "playfield_composition": "信号格、灯阵、编码轨",
        "camera_profile": "signal_grid_console",
        "hud_model": "signal_combo_accuracy",
    },
    "rain": {
        "playfield_composition": "窗格、雨滴轨、疏密节奏",
        "camera_profile": "rain_window_grid",
        "hud_model": "rain_pattern_flow",
    },
    "kitchen": {
        "playfield_composition": "锅碗声部、生活乐队、节奏接力",
        "camera_profile": "kitchen_band_table",
        "hud_model": "band_part_accuracy",
    },
    "mountain": {
        "playfield_composition": "山路节点、上下坡、登顶旗",
        "camera_profile": "vertical_route_map",
        "hud_model": "route_position_direction",
    },
    "cloud": {
        "playfield_composition": "云梯楼层、升降按钮、云端目标",
        "camera_profile": "cloud_elevator_lift",
        "hud_model": "height_floor_direction",
    },
    "bamboo": {
        "playfield_composition": "竹节层级、风铃节点、旋律路线",
        "camera_profile": "bamboo_scroll_path",
        "hud_model": "route_position_direction",
    },
    "lantern": {
        "playfield_composition": "灯塔楼层、灯火目标、旋律点亮",
        "camera_profile": "lantern_tower_vertical",
        "hud_model": "height_lantern_progress",
    },
    "star": {
        "playfield_composition": "星环靶、准星、唱名星核",
        "camera_profile": "aiming_target_arena",
        "hud_model": "reticle_hit_singback",
    },
    "flower": {
        "playfield_composition": "花瓣靶、绽放层级、轻声唱回",
        "camera_profile": "garden_bloom_focus",
        "hud_model": "bloom_hit_singback",
    },
    "archery": {
        "playfield_composition": "弓箭跑道、横向靶位、快速瞄准",
        "camera_profile": "archery_range_lane",
        "hud_model": "reticle_hit_singback",
    },
    "bubble": {
        "playfield_composition": "漂浮泡泡、轻点击破、唱名弹跳",
        "camera_profile": "bubble_float_field",
        "hud_model": "bubble_chain_singback",
    },
    "casebook": {
        "playfield_composition": "案卷、嫌疑卡、证据贴",
        "camera_profile": "detective_desk_closeup",
        "hud_model": "clue_suspect_evidence",
    },
    "museum": {
        "playfield_composition": "展柜、藏品标签、家族归档",
        "camera_profile": "museum_gallery_pan",
        "hud_model": "collection_family_evidence",
    },
    "forest": {
        "playfield_composition": "森林声源、回声波纹、线索足迹",
        "camera_profile": "forest_echo_clearing",
        "hud_model": "echo_source_evidence",
    },
    "studio": {
        "playfield_composition": "调音台、波形、推子证据",
        "camera_profile": "studio_mixer_console",
        "hud_model": "waveform_trait_mix",
    },
    "theater": {
        "playfield_composition": "皮影舞台、剪影声源、声影配对",
        "camera_profile": "shadow_theater_stage",
        "hud_model": "shadow_source_evidence",
    },
    "map": {
        "playfield_composition": "藏宝图时间轴、段落岛屿、宝箱终点",
        "camera_profile": "timeline_treasure_map",
        "hud_model": "timeline_card_progress",
    },
    "constellation": {
        "playfield_composition": "星图航线、段落星点、主题回归星门",
        "camera_profile": "constellation_timeline",
        "hud_model": "timeline_card_progress",
    },
    "gallery": {
        "playfield_composition": "音乐展馆、分区展牌、段落导览线",
        "camera_profile": "gallery_walkthrough",
        "hud_model": "timeline_card_progress",
    },
    "train": {
        "playfield_composition": "音乐列车、段落站台、重复返站路线",
        "camera_profile": "train_route_timeline",
        "hud_model": "timeline_card_progress",
    },
    "stage": {
        "playfield_composition": "剧场分幕、灯光段落、剧本结构卡",
        "camera_profile": "stage_script_timeline",
        "hud_model": "timeline_card_progress",
    },
    "rhythm_table": {
        "playfield_composition": "节奏积木桌、拍点槽、小节轨道和试听波纹",
        "camera_profile": "studio_tile_table",
        "hud_model": "constraint_checklist_progress",
    },
    "melody_garden": {
        "playfield_composition": "旋律花园、唱名花卡、上行下行藤蔓和结束音花台",
        "camera_profile": "garden_phrase_track",
        "hud_model": "constraint_checklist_progress",
    },
}


EXPERIENCE_VARIANTS: dict[str, dict[str, Any]] = {
    "castle_gate": {
        "experience_variant_id": "pulsing_shield_guard",
        "template_id": "beat_guardian_core",
        "play_mode": "gate",
        "game_genre": "arcade_guardian",
        "scene_goal": "维持中央护盾，在第 1 拍收缩到最亮瞬间同步充能并清掉靠近怪物。",
        "main_object": "pulsing_shield",
        "interaction_feedback": "完美充能时护盾震波推开并清除靠近的弱拍怪物。",
        "failure_feedback": "早按、晚按或弱拍误按时护盾出现裂缝，下一小节重新预判。",
        "reward_loop": "精准充能触发震波清怪，清空怪物后护盾稳定。",
        "student_mission": "看怪物靠近，听弱拍，在第 1 拍到来前准备好同步充能。",
        "teacher_reason": "充能护盾把重音的延伸与周期变成可观察的收缩过程，训练学生预判强拍而不是滞后反应。",
        "skin_family": "race_world",
        "layout_variant": "pulsing_shield",
    },
    "dragon_boat": {
        "experience_variant_id": "dragon_boat_race",
        "template_id": "beat_guardian_core",
        "play_mode": "race",
        "game_genre": "arcade_race",
        "scene_goal": "让龙舟跟随鼓点冲过终点。",
        "main_object": "dragon_boat",
        "interaction_feedback": "按准强拍后龙舟加速、鼓面发光、水花飞溅。",
        "failure_feedback": "抢拍或漏拍时龙舟减速，鼓手提醒下一拍。",
        "reward_loop": "连续命中积累鼓点能量，触发冲刺。",
        "student_mission": "跟上鼓点，让龙舟冲过终点。",
        "teacher_reason": "强拍天然对应龙舟鼓点推进，适合低年级二拍子律动。",
        "skin_family": "race_world",
        "layout_variant": "river_race",
    },
    "train_conductor": {
        "experience_variant_id": "train_dispatch",
        "template_id": "beat_guardian_core",
        "play_mode": "station",
        "game_genre": "timing_dispatch",
        "scene_goal": "按准拍点，让节拍列车准时进站。",
        "main_object": "train",
        "interaction_feedback": "目标拍命中时车轮发光、列车前进一站。",
        "failure_feedback": "节拍不稳时列车错过站台，下一站重新对齐。",
        "reward_loop": "连续准点让所有车厢亮灯，完成发车。",
        "student_mission": "听稳车轮拍，只在站台拍点发车。",
        "teacher_reason": "列车进站能把稳定拍和速度感转化为低年级容易理解的准时任务。",
        "skin_family": "race_world",
        "layout_variant": "station_lane",
    },
    "stage_light": {
        "experience_variant_id": "stage_spotlight",
        "template_id": "beat_guardian_core",
        "play_mode": "spotlight",
        "game_genre": "performance_cue",
        "scene_goal": "按准节拍点亮舞台追光。",
        "main_object": "spotlight",
        "interaction_feedback": "目标拍命中时主灯扫到演员，舞台光圈扩大。",
        "failure_feedback": "抢拍时追光偏移，下一拍显示站位提示。",
        "reward_loop": "连续命中完成舞台灯光秀。",
        "student_mission": "稳住拍子，帮舞台灯光准时亮起。",
        "teacher_reason": "追光适合把进入时机、合奏准备和表演感连接起来。",
        "skin_family": "pulse_world",
        "layout_variant": "spotlight_stage",
    },
    "space_orbit": {
        "experience_variant_id": "space_orbit_lock",
        "template_id": "beat_guardian_core",
        "play_mode": "orbit",
        "game_genre": "orbit_timing",
        "scene_goal": "按准拍点，让星球稳定进入轨道窗口。",
        "main_object": "orbit_planet",
        "interaction_feedback": "命中时轨道锁定、星球留下光尾。",
        "failure_feedback": "错拍时星球偏离轨道，给出下一窗口提示。",
        "reward_loop": "连续命中完成整圈星轨。",
        "student_mission": "看星球轨道收紧，在第 1 拍窗口同步充能。",
        "teacher_reason": "轨道窗口适合训练少提示条件下的内在稳定拍。",
        "skin_family": "target_world",
        "layout_variant": "orbit_window",
    },
    "rhythm_radio": {
        "experience_variant_id": "rhythm_radio_transmission",
        "template_id": "rhythm_echo_core",
        "play_mode": "radio",
        "game_genre": "memory_echo",
        "scene_goal": "听示范电波，再把长短节奏完整传回飞船。",
        "main_object": "radio_pager_console",
        "interaction_feedback": "拍准时电波块点亮，飞船对接轨道推进。",
        "failure_feedback": "节奏不稳时触发警报波形，并保留轨迹提示重听。",
        "reward_loop": "准确率提升后获得飞船对接徽章。",
        "student_mission": "先听完整电波，再把节奏稳稳传回去。",
        "teacher_reason": "节奏电波传呼机适合长短节奏听辨、记忆复刻和时间轴复盘。",
        "skin_family": "target_world",
        "layout_variant": "signal_console",
    },
    "echo_cave": {
        "experience_variant_id": "echo_cave_memory",
        "template_id": "rhythm_echo_core",
        "play_mode": "cave",
        "game_genre": "echo_memory",
        "scene_goal": "听山洞回声，记住后拍回节奏。",
        "main_object": "echo_wave",
        "interaction_feedback": "拍准时回声波纹一圈圈返回。",
        "failure_feedback": "漏拍时波纹断开，提示再听回声尾巴。",
        "reward_loop": "连续复刻让山洞水晶发光。",
        "student_mission": "让山洞听见一样的回声。",
        "teacher_reason": "回声场景强调先听后记，适合延迟记忆训练。",
        "skin_family": "pulse_world",
        "layout_variant": "echo_cave",
    },
    "robot_signal": {
        "experience_variant_id": "robot_signal_grid",
        "template_id": "rhythm_echo_core",
        "play_mode": "signal",
        "game_genre": "signal_code",
        "scene_goal": "复刻节奏信号，帮机器人完成编码。",
        "main_object": "signal_robot",
        "interaction_feedback": "拍准时信号灯格逐个点亮。",
        "failure_feedback": "错误输入会标红对应信号格，允许重听修正。",
        "reward_loop": "整条编码正确后机器人启动舞步。",
        "student_mission": "把听到的节奏变成准确的信号灯。",
        "teacher_reason": "信号编码适合休止、切分和节奏结构辨认。",
        "skin_family": "target_world",
        "layout_variant": "signal_grid",
    },
    "rain_window": {
        "experience_variant_id": "rain_window_pattern",
        "template_id": "rhythm_echo_core",
        "play_mode": "rain",
        "game_genre": "pattern_flow",
        "scene_goal": "听雨点节奏，在窗格上拍出疏密变化。",
        "main_object": "rain_window",
        "interaction_feedback": "拍准时雨滴落在对应窗格，水纹扩散。",
        "failure_feedback": "疏密不准时窗格保留痕迹，提示听长短。",
        "reward_loop": "完成节奏后窗外彩虹出现。",
        "student_mission": "听出雨点的长短，再拍回窗格。",
        "teacher_reason": "雨点窗台适合柔和材料里的长短时值和疏密感。",
        "skin_family": "trail_world",
        "layout_variant": "rain_grid",
    },
    "kitchen_band": {
        "experience_variant_id": "kitchen_band_groove",
        "template_id": "rhythm_echo_core",
        "play_mode": "kitchen",
        "game_genre": "found_sound_band",
        "scene_goal": "用生活声音复刻节奏，组起厨房乐队。",
        "main_object": "kitchen_band",
        "interaction_feedback": "拍准时锅碗声部加入合奏。",
        "failure_feedback": "节奏散掉时只保留已准的声部，提示重拍缺口。",
        "reward_loop": "所有声部合上后厨房乐队开演。",
        "student_mission": "把节奏拍准，让厨房乐队一起进来。",
        "teacher_reason": "厨房乐队把节奏学习迁移到生活声音和创意实践。",
        "skin_family": "pulse_world",
        "layout_variant": "kitchen_band",
    },
    "mountain_steps": {
        "experience_variant_id": "mountain_pitch_climb",
        "template_id": "pitch_ladder_core",
        "play_mode": "mountain",
        "game_genre": "map_climb",
        "scene_goal": "听音高方向，沿山路走到正确节点。",
        "main_object": "mountain_path",
        "interaction_feedback": "选对高低时角色向上或向下移动。",
        "failure_feedback": "方向不稳时停在原地，提示再听第二个音。",
        "reward_loop": "完成路线后插上登山旗。",
        "student_mission": "听声音往上还是往下，帮角色走山路。",
        "teacher_reason": "山路是音高方向最直观的空间隐喻。",
        "skin_family": "trail_world",
        "layout_variant": "trail_map",
    },
    "cloud_elevator": {
        "experience_variant_id": "cloud_elevator_pitch",
        "template_id": "pitch_ladder_core",
        "play_mode": "cloud",
        "game_genre": "height_elevator",
        "scene_goal": "听音高，控制云梯升降到正确楼层。",
        "main_object": "cloud_elevator",
        "interaction_feedback": "判断正确时云梯升降并停靠发光楼层。",
        "failure_feedback": "楼层错位时云朵变慢，提示比较两个音。",
        "reward_loop": "连续正确让云梯升到音乐云顶。",
        "student_mission": "听第二个音，把云梯开到对的高度。",
        "teacher_reason": "云梯适合低年级把音高高低理解为空间升降。",
        "skin_family": "trail_world",
        "layout_variant": "cloud_elevator",
    },
    "bamboo_ladder": {
        "experience_variant_id": "bamboo_ladder_melody",
        "template_id": "pitch_ladder_core",
        "play_mode": "bamboo",
        "game_genre": "melody_route",
        "scene_goal": "把听到的唱名放进竹节路线。",
        "main_object": "bamboo_ladder",
        "interaction_feedback": "选对时竹节发光、风铃响起。",
        "failure_feedback": "唱名位置不稳时竹叶轻摆，提示复听。",
        "reward_loop": "整条路线正确后竹林亮起。",
        "student_mission": "听清唱名，让竹节一格格亮起来。",
        "teacher_reason": "竹节爬梯适合中国风材料和唱名定位。",
        "skin_family": "trail_world",
        "layout_variant": "trail_map",
    },
    "lantern_tower": {
        "experience_variant_id": "lantern_tower_pitch",
        "template_id": "pitch_ladder_core",
        "play_mode": "lantern",
        "game_genre": "tower_light",
        "scene_goal": "听短旋律，按音高点亮灯塔楼层。",
        "main_object": "lantern_tower",
        "interaction_feedback": "每个音定位正确时对应灯火亮起。",
        "failure_feedback": "楼层错时灯火半亮，提示听整组音的走向。",
        "reward_loop": "点亮整座灯塔完成旋律路线。",
        "student_mission": "把旋律听成灯塔楼层，一层层点亮。",
        "teacher_reason": "灯塔点灯适合短旋律记忆和音列复述。",
        "skin_family": "target_world",
        "layout_variant": "lantern_tower",
    },
    "star_target": {
        "experience_variant_id": "star_solfege_target",
        "template_id": "solfege_target_core",
        "play_mode": "star",
        "game_genre": "target_range",
        "scene_goal": "听目标音，击中正确唱名星靶。",
        "main_object": "star_target",
        "interaction_feedback": "击中后星轨亮起并提示唱回。",
        "failure_feedback": "打偏时准星回弹，提示先心里唱名。",
        "reward_loop": "连续命中组成星座徽章。",
        "student_mission": "先在心里唱准，再击中唱名星靶。",
        "teacher_reason": "星靶适合三音组、五声音阶的唱名听辨。",
        "skin_family": "target_world",
        "layout_variant": "target_arena",
    },
    "flower_bloom": {
        "experience_variant_id": "flower_solfege_bloom",
        "template_id": "solfege_target_core",
        "play_mode": "flower",
        "game_genre": "gentle_target",
        "scene_goal": "听准唱名，让对应花朵开放。",
        "main_object": "solfege_flower",
        "interaction_feedback": "命中后花瓣展开，唱回后花心发光。",
        "failure_feedback": "选错时花苞不关闭，只提示再听一遍。",
        "reward_loop": "花园全部开放后完成合唱小花园。",
        "student_mission": "轻轻听、轻轻唱，让花朵开出来。",
        "teacher_reason": "花朵绽放适合低年级温和反馈和集体模唱。",
        "skin_family": "target_world",
        "layout_variant": "bloom_garden",
    },
    "lantern_target": {
        "experience_variant_id": "lantern_solfege_target",
        "template_id": "solfege_target_core",
        "play_mode": "lantern",
        "game_genre": "festival_target",
        "scene_goal": "听唱名，点亮正确灯笼靶。",
        "main_object": "lantern_target",
        "interaction_feedback": "击中时灯火变亮，唱回后灯笼升起。",
        "failure_feedback": "错靶时灯笼轻晃，提示听音高位置。",
        "reward_loop": "连续点亮组成节庆灯阵。",
        "student_mission": "听准唱名，点亮正确灯笼。",
        "teacher_reason": "灯笼靶会适合民歌、中国风材料里的唱名训练。",
        "skin_family": "target_world",
        "layout_variant": "lantern_target",
    },
    "archery_field": {
        "experience_variant_id": "archery_solfege_range",
        "template_id": "solfege_target_core",
        "play_mode": "archery",
        "game_genre": "precision_target",
        "scene_goal": "快速听辨唱名，把箭射向正确靶心。",
        "main_object": "music_arrow",
        "interaction_feedback": "命中时箭矢定靶、连击环扩大。",
        "failure_feedback": "错靶时箭落在旁边，提示复听目标音。",
        "reward_loop": "连续命中完成神射手徽章。",
        "student_mission": "听准、瞄准、命中，再把音唱回。",
        "teacher_reason": "弓箭靶场适合中高年级快速听辨和短音组记忆。",
        "skin_family": "target_world",
        "layout_variant": "archery_range",
    },
    "bubble_pop": {
        "experience_variant_id": "bubble_solfege_pop",
        "template_id": "solfege_target_core",
        "play_mode": "bubble",
        "game_genre": "light_target",
        "scene_goal": "听目标唱名，点破正确泡泡。",
        "main_object": "solfege_bubble",
        "interaction_feedback": "点中泡泡会弹开并发出轻亮音效。",
        "failure_feedback": "错点泡泡会漂走，提示先慢慢唱一遍。",
        "reward_loop": "连续击中形成泡泡旋律串。",
        "student_mission": "听见哪个唱名，就点破哪个泡泡。",
        "teacher_reason": "泡泡唱名适合低年级轻松入门和轻声模唱。",
        "skin_family": "target_world",
        "layout_variant": "bubble_field",
    },
    "sound_casebook": {
        "experience_variant_id": "sound_casebook_detective",
        "template_id": "timbre_detective_core",
        "play_mode": "casebook",
        "game_genre": "detective_mystery",
        "scene_goal": "听声音证物，找出嫌疑乐器和音色证据。",
        "main_object": "casebook",
        "interaction_feedback": "选对后证据贴盖章，案卷推进。",
        "failure_feedback": "证据不足时保留选择，提示换一个音色词。",
        "reward_loop": "破案后获得侦探徽章。",
        "student_mission": "听证物、找嫌疑人、贴证据。",
        "teacher_reason": "声音案卷适合标准音色听辨和乐器识别。",
        "skin_family": "casebook_world",
        "layout_variant": "detective_desk",
    },
    "museum_clues": {
        "experience_variant_id": "museum_instrument_clues",
        "template_id": "timbre_detective_core",
        "play_mode": "museum",
        "game_genre": "collection_sorting",
        "scene_goal": "听声音，把乐器藏品归入正确展柜。",
        "main_object": "museum_case",
        "interaction_feedback": "归档正确时展柜标签亮起。",
        "failure_feedback": "归错时展柜半透明，提示听发声方式。",
        "reward_loop": "完成一排展柜获得馆长印章。",
        "student_mission": "帮博物馆把声音藏品归档。",
        "teacher_reason": "博物馆适合乐器分类、发声方式和文化理解。",
        "skin_family": "casebook_world",
        "layout_variant": "museum_gallery",
    },
    "forest_echo": {
        "experience_variant_id": "forest_timbre_echo",
        "template_id": "timbre_detective_core",
        "play_mode": "forest",
        "game_genre": "source_hunt",
        "scene_goal": "听森林回声，找到隐藏的声音来源。",
        "main_object": "forest_echo",
        "interaction_feedback": "选对时足迹亮起、波纹指向声源。",
        "failure_feedback": "错选时波纹散开，提示比较明亮/柔和。",
        "reward_loop": "找到所有声源后森林合奏响起。",
        "student_mission": "跟着回声波纹找到声音来源。",
        "teacher_reason": "森林回声适合自然声与乐器音色对比。",
        "skin_family": "casebook_world",
        "layout_variant": "forest_echo",
    },
    "studio_mixer": {
        "experience_variant_id": "studio_mixer_timbre",
        "template_id": "timbre_detective_core",
        "play_mode": "studio",
        "game_genre": "audio_mixer",
        "scene_goal": "听声音特征，用调音台找出音色证据。",
        "main_object": "mixer_console",
        "interaction_feedback": "证据正确时波形变清晰、推子锁定。",
        "failure_feedback": "证据不准时波形仍模糊，提示听起音和延音。",
        "reward_loop": "完成调音后解锁清晰音轨。",
        "student_mission": "像小录音师一样听出音色特征。",
        "teacher_reason": "录音棚适合高年级理解明亮度、起音和延音。",
        "skin_family": "casebook_world",
        "layout_variant": "studio_mixer",
    },
    "shadow_theater": {
        "experience_variant_id": "shadow_theater_timbre",
        "template_id": "timbre_detective_core",
        "play_mode": "theater",
        "game_genre": "shadow_story",
        "scene_goal": "听声影线索，匹配正确民族乐器角色。",
        "main_object": "shadow_stage",
        "interaction_feedback": "匹配正确时剪影登场，声影合一。",
        "failure_feedback": "错配时剪影退回幕布，提示听发声质感。",
        "reward_loop": "所有角色登场后完成声影小剧场。",
        "student_mission": "让每个声音找到自己的影子。",
        "teacher_reason": "声影剧场适合民族乐器、故事化听赏和审美表达。",
        "skin_family": "casebook_world",
        "layout_variant": "shadow_theater",
    },
    "treasure_map": {
        "experience_variant_id": "treasure_map_form",
        "template_id": "form_treasure_core",
        "play_mode": "map",
        "game_genre": "form_treasure_map",
        "scene_goal": "听段落，沿藏宝图点亮正确曲式路线。",
        "main_object": "treasure_timeline",
        "interaction_feedback": "结构卡放对时段落岛屿点亮，宝箱路线前进。",
        "failure_feedback": "顺序不稳时路线停住，提示复听主题是否回来。",
        "reward_loop": "完整曲式路线正确后打开结构宝箱。",
        "student_mission": "听出 A、B 段关系，让藏宝图连成完整路线。",
        "teacher_reason": "藏宝图能把抽象曲式变成可视路线，适合 ABA 入门。",
        "skin_family": "trail_world",
        "layout_variant": "trail_map",
    },
    "constellation_path": {
        "experience_variant_id": "constellation_form",
        "template_id": "form_treasure_core",
        "play_mode": "constellation",
        "game_genre": "form_star_route",
        "scene_goal": "让主题星多次返回，连成回旋星图。",
        "main_object": "star_route",
        "interaction_feedback": "主题回归时星门发光，航线延伸。",
        "failure_feedback": "新材料和主题混淆时星点变暗，提示复听主题动机。",
        "reward_loop": "回旋结构完成后点亮星座徽章。",
        "student_mission": "找到不断回来的主题星。",
        "teacher_reason": "星图航线适合表现回旋曲式中主题反复返回。",
        "skin_family": "target_world",
        "layout_variant": "target_arena",
    },
    "museum_gallery": {
        "experience_variant_id": "museum_gallery_form",
        "template_id": "form_treasure_core",
        "play_mode": "gallery",
        "game_genre": "form_gallery_walk",
        "scene_goal": "把段落放进正确展厅，完成音乐结构导览。",
        "main_object": "gallery_timeline",
        "interaction_feedback": "展牌匹配后盖章，展线继续开放。",
        "failure_feedback": "展厅不对时提示比较主题、对比和再现。",
        "reward_loop": "全展线完成后获得策展人徽章。",
        "student_mission": "像策展人一样给音乐段落分区。",
        "teacher_reason": "展馆场景适合听赏课中的结构归纳。",
        "skin_family": "casebook_world",
        "layout_variant": "detective_desk",
    },
    "train_route": {
        "experience_variant_id": "train_route_form",
        "template_id": "form_treasure_core",
        "play_mode": "train",
        "game_genre": "form_train_route",
        "scene_goal": "让音乐列车按曲式站台正确到站。",
        "main_object": "form_train",
        "interaction_feedback": "相同段落返站，列车灯逐节点亮。",
        "failure_feedback": "站台选择错误时列车等待复听。",
        "reward_loop": "列车跑完整条曲式路线后抵达终点站。",
        "student_mission": "听出列车是不是回到主题站。",
        "teacher_reason": "列车路线能表现重复、对比和返回。",
        "skin_family": "race_world",
        "layout_variant": "river_race",
    },
    "stage_script": {
        "experience_variant_id": "stage_script_form",
        "template_id": "form_treasure_core",
        "play_mode": "stage",
        "game_genre": "form_stage_script",
        "scene_goal": "按音乐段落排好剧场分幕。",
        "main_object": "stage_script",
        "interaction_feedback": "分幕正确时追光亮起，剧本翻页。",
        "failure_feedback": "段落命名不稳时舞台保留半亮提示。",
        "reward_loop": "终幕亮灯后完成曲式演出。",
        "student_mission": "听出每一幕是主题、对比还是再现。",
        "teacher_reason": "剧场分幕适合把段落命名和审美表达结合起来。",
        "skin_family": "pulse_world",
        "layout_variant": "pulse_stage",
    },
    "composition_studio": {
        "experience_variant_id": "composition_studio_lab",
        "template_id": "composition_puzzle_core",
        "play_mode": "studio",
        "game_genre": "constrained_composition_puzzle",
        "scene_goal": "用节奏和旋律素材卡拼成完整音乐短句。",
        "main_object": "composition_track",
        "interaction_feedback": "素材卡落入轨道后小节灯亮起，试听时拍点和音高依次高亮。",
        "failure_feedback": "规则未满足时提示气泡指出缺少的音乐要素。",
        "reward_loop": "约束通过并教师确认后点亮创编徽章。",
        "student_mission": "拖卡、试听、修改，让短句听起来完整。",
        "teacher_reason": "创编教室能同时承载节奏、旋律与综合短句创作。",
        "skin_family": "pulse_world",
        "layout_variant": "pulse_stage",
    },
    "rhythm_tile_table": {
        "experience_variant_id": "rhythm_tile_table_lab",
        "template_id": "composition_puzzle_core",
        "play_mode": "rhythm_table",
        "game_genre": "rhythm_composition_table",
        "scene_goal": "用时值、休止、附点或切分卡填满节奏小节。",
        "main_object": "rhythm_tile_track",
        "interaction_feedback": "节奏卡吸附到拍点槽，试听时波纹按时值推进。",
        "failure_feedback": "小节未满或缺少目标节奏要素时拍点槽轻亮提示。",
        "reward_loop": "完整节奏短句通过后获得节奏积木星章。",
        "student_mission": "把节奏积木拼成稳定又有变化的短句。",
        "teacher_reason": "积木桌把抽象时值转成可拖拽格子，适合节奏创编。",
        "skin_family": "pulse_world",
        "layout_variant": "pulse_stage",
    },
    "melody_garden": {
        "experience_variant_id": "melody_garden_lab",
        "template_id": "composition_puzzle_core",
        "play_mode": "melody_garden",
        "game_genre": "melody_composition_garden",
        "scene_goal": "用唱名花卡拼出有走向、有结束感的旋律短句。",
        "main_object": "melody_vine_track",
        "interaction_feedback": "唱名卡落位后藤蔓连接，上行下行随试听发光。",
        "failure_feedback": "旋律过于静止或结束音不稳时花台给出调整提示。",
        "reward_loop": "旋律短句通过后花章开放。",
        "student_mission": "让旋律花卡连成会唱的短句。",
        "teacher_reason": "旋律花园适合表现音高走向、结束音和短句感。",
        "skin_family": "target_world",
        "layout_variant": "target_arena",
    },
}


def get_experience_variant(skin_id: str, template_id: str | None = None) -> dict[str, Any] | None:
    variant = EXPERIENCE_VARIANTS.get(str(skin_id or ""))
    if not variant:
        return None
    if template_id and variant.get("template_id") != template_id:
        return None
    enriched = deepcopy(variant)
    play_mode = str(enriched.get("play_mode") or "")
    enriched["play_structure"] = deepcopy(PLAY_MODE_STRUCTURES.get(play_mode, {}))
    return enriched


def list_experience_variants(template_id: str | None = None) -> list[dict[str, Any]]:
    variants = [
        get_experience_variant(skin_id)
        for skin_id in EXPERIENCE_VARIANTS
        if template_id is None or EXPERIENCE_VARIANTS[skin_id].get("template_id") == template_id
    ]
    return [variant for variant in variants if variant]


def apply_experience_variant(config: dict[str, Any], template_id: str) -> dict[str, Any]:
    skin_id = str(config.get("skin_id") or "")
    variant = get_experience_variant(skin_id, template_id) or {}
    if not variant:
        return config
    structure = variant.get("play_structure", {}) if isinstance(variant.get("play_structure"), dict) else {}
    config["experience_variant"] = deepcopy(variant)
    config["experience_variant_id"] = variant["experience_variant_id"]
    config["skin_play_mode"] = variant["play_mode"]
    # Variants describe the skin's moment-to-moment staging, but the template
    # blueprint owns the stable genre/HUD/camera contract used by quality gates.
    config["variant_game_genre"] = variant.get("game_genre", "")
    config["variant_camera_profile"] = structure.get("camera_profile", "")
    config["variant_hud_model"] = structure.get("hud_model", "")
    config["playfield_composition"] = structure.get("playfield_composition", "")
    config["scene_goal"] = variant.get("scene_goal", "")
    config["main_object"] = variant.get("main_object", "")
    config["interaction_feedback"] = variant.get("interaction_feedback", "")
    config["failure_feedback"] = variant.get("failure_feedback", "")
    config["reward_loop"] = variant.get("reward_loop", "")
    config["student_mission"] = variant.get("student_mission", "")
    config["template_match_reason"] = variant.get("teacher_reason", "")
    tags = list(config.get("distinctiveness_tags") or [])
    for tag in (variant["experience_variant_id"], variant["play_mode"], variant.get("game_genre", "")):
        if tag and tag not in tags:
            tags.append(str(tag))
    config["distinctiveness_tags"] = tags
    if isinstance(config.get("scene_config"), dict):
        config["scene_config"].update(experience_variant_scene_fields(config))
    return config


def experience_variant_scene_fields(config: dict[str, Any]) -> dict[str, Any]:
    variant = config.get("experience_variant") if isinstance(config.get("experience_variant"), dict) else {}
    structure = variant.get("play_structure", {}) if isinstance(variant.get("play_structure"), dict) else {}
    return {
        "experience_variant_id": config.get("experience_variant_id", ""),
        "experience_variant": deepcopy(variant),
        "skin_play_mode": config.get("skin_play_mode", variant.get("play_mode", "")),
        "variant_game_genre": config.get("variant_game_genre", variant.get("game_genre", "")),
        "variant_camera_profile": config.get("variant_camera_profile", structure.get("camera_profile", "")),
        "variant_hud_model": config.get("variant_hud_model", structure.get("hud_model", "")),
        "playfield_composition": config.get("playfield_composition") or structure.get("playfield_composition", ""),
        "scene_goal": config.get("scene_goal") or variant.get("scene_goal", ""),
        "main_object": config.get("main_object") or variant.get("main_object", ""),
        "interaction_feedback": config.get("interaction_feedback") or variant.get("interaction_feedback", ""),
        "failure_feedback": config.get("failure_feedback") or variant.get("failure_feedback", ""),
        "reward_loop": config.get("reward_loop") or variant.get("reward_loop", ""),
        "student_mission": config.get("student_mission") or variant.get("student_mission", ""),
    }
