export { default as VirtualInstrumentPlayer } from "./VirtualInstrumentPlayer.vue";
export { default as PercussionGrid } from "./PercussionGrid.vue";
export { default as FixedTabletStage } from "./FixedTabletStage.vue";
export { default as InstrumentTouchOverlay } from "./InstrumentTouchOverlay.vue";
export { default as InstrumentSkinCanvas } from "./InstrumentSkinCanvas.vue";
export { default as ClassroomInstrumentActivity } from "./ClassroomInstrumentActivity.vue";
export { default as ClassroomActivityTeacherBar } from "./ClassroomActivityTeacherBar.vue";
export { default as InstrumentReviewWizard } from "./InstrumentReviewWizard.vue";
export { default as RealMetronome } from "./RealMetronome.vue";
export type { VirtualInstrumentPlayerProps } from "./types";
export * from "../core/audioEngine";
export * from "../core/performanceRecorder";
export * from "../core/performanceRecordingStore";
export * from "../core/virtualInstrumentCatalog";
export * from "../core/malletLayout";
export * from "../core/pianoLayout";
export * from "../core/percussionGrid";
export * from "../core/fixedTabletStage";
export * from "../core/instrumentTouchMap";
export * from "../core/instrumentSkinCalibration";
export * from "../core/metronome";
export * from "../core/classroomInstrumentActivity";
export * from "../core/reviewWizard";
