<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue";
import { createClassroomActivitySession, finishClassroomActivity, recordClassroomActivityTap, type ClassroomActivitySession, type ClassroomInstrumentActivityConfig, type ClassroomPerformanceEvidence } from "../core/classroomInstrumentActivity";
import { beatsPerBar } from "../core/metronome";
import FixedTabletStage from "./FixedTabletStage.vue";
import PercussionGrid from "./PercussionGrid.vue";
import RealMetronome from "./RealMetronome.vue";
import VirtualInstrumentPlayer from "./VirtualInstrumentPlayer.vue";
const props=defineProps<{config:ClassroomInstrumentActivityConfig;showTeacherControls?:boolean}>();
const emit=defineEmits<{evidence:[value:ClassroomPerformanceEvidence];activitystart:[];activitystop:[];error:[error:Error]}>();
const phase=ref<"idle"|"count_in"|"demo"|"performing"|"complete">("idle");
const player=ref<any>(null);const grid=ref<any>(null);const metronome=ref<any>(null);let session:ClassroomActivitySession|null=null;let performanceStart=0;let timers:number[]=[];
const modeLabels={free_play:"自由演奏",steady_beat:"稳定拍",echo:"听后复刻",ensemble_cue:"合奏提示"};
const guidance=computed(()=>props.config.mode==="free_play"?"自由探索音色，网页不自动评分。":props.config.mode==="echo"?"先完整听示范，示范结束后再复刻。":props.config.mode==="ensemble_cue"?"按照进入、保持、停止提示演奏。":"在稳定拍点上演奏，网页只记录客观时间证据。");
function clear(){timers.forEach(window.clearTimeout);timers=[];metronome.value?.stop()}
async function prepareTarget(){if(props.config.target.type==="instrument")await player.value?.initialize();else await grid.value?.initialize()}
function demoDurationMs(){const beatMs=60000/props.config.metronome.bpm;return Math.max(beatMs,...(props.config.demoSequence??[]).map(item=>(item.beatOffset+item.durationBeats)*beatMs))}
function playDemo(){const beatMs=60000/props.config.metronome.bpm;for(const item of props.config.demoSequence??[]){timers.push(window.setTimeout(()=>{if(props.config.target.type==="instrument")player.value?.triggerZone(item.zoneId,item.durationBeats*beatMs);else grid.value?.triggerTile(item.zoneId,item.durationBeats*beatMs)},item.beatOffset*beatMs))}}
async function beginCountIn(){phase.value="count_in";const beatMs=60000/props.config.metronome.bpm;const countInMs=beatsPerBar(props.config.metronome.meter)*beatMs;const maxBeat=Math.max(1,...(props.config.demoSequence??[]).map(item=>item.beatOffset+item.durationBeats));const bars=Math.ceil(maxBeat/beatsPerBar(props.config.metronome.meter));await metronome.value?.play(props.config.metronome,bars);timers.push(window.setTimeout(()=>{phase.value="performing";performanceStart=performance.now()},countInMs))}
async function start(){clear();session=createClassroomActivitySession(props.config);emit("activitystart");try{await prepareTarget();if(props.config.mode==="free_play"){phase.value="performing";performanceStart=performance.now();return}if(props.config.mode==="echo"){phase.value="demo";playDemo();timers.push(window.setTimeout(()=>void beginCountIn(),demoDurationMs()+180));return}await beginCountIn()}catch(error){phase.value="idle";const normalized=error instanceof Error?error:new Error(String(error));emit("error",normalized)}}
function handleTap(zoneId:string){if(phase.value!=="performing"||!session)return;recordClassroomActivityTap(session,{zoneId,elapsedMs:performance.now()-performanceStart})}
function stop(){clear();player.value?.stopAll();if(session)emit("evidence",finishClassroomActivity(session));session=null;phase.value="complete";emit("activitystop")}
onBeforeUnmount(clear);
</script>
<template><section class="activity-shell" :data-mode="config.mode"><header><div><p>CLASSROOM PLAY MODE</p><h2>{{ modeLabels[config.mode] }}</h2></div><div class="status"><RealMetronome ref="metronome" @error="error=>emit('error',error)"/><span :data-phase="phase">{{ phase }}</span></div></header><p class="guidance">{{ guidance }}</p><FixedTabletStage @blocked="stop"><div class="stage-content"><div v-if="phase==='count_in'" class="cue">预备拍 · 不计入学生演奏</div><div v-if="phase==='demo'" class="cue">听示范 · 暂不演奏</div><div v-if="config.mode==='ensemble_cue'&&phase==='performing'" class="cue cue--go">进入 / 保持 / 停止</div><PercussionGrid v-if="config.target.type==='percussion_grid'" ref="grid" :tiles="config.target.tiles" @noteon="tile=>handleTap(tile.zoneId)"/><VirtualInstrumentPlayer v-else ref="player" :instrument-id="config.target.instrumentId" :disabled="phase!=='performing'" :auto-initialize="false" :show-controls="false" @noteon="zone=>handleTap(zone.id)"/></div></FixedTabletStage><footer><button @click="start">开始</button><button @click="stop">结束并输出证据</button><small>音乐表现、合作、力度和最终通过必须由教师判断。</small></footer></section></template>
<style scoped>.activity-shell{padding:18px;color:#f1e8d7;background:#101715;border-radius:26px}.activity-shell header{display:flex;justify-content:space-between;align-items:center}.activity-shell header p{margin:0;color:#d98b50;font-size:10px;letter-spacing:.18em}.activity-shell h2{margin:4px 0;font:500 32px/1 "Songti SC",serif}.status{display:flex;gap:7px}.activity-shell header span{padding:7px 11px;border-radius:999px;background:#fff1;font-size:11px}.guidance{color:#b9af9e;font-size:12px}.activity-shell :deep(.tablet-host){height:min(68vw,768px)}.stage-content{position:relative;width:1024px;height:768px;padding:22px}.stage-content>:deep(.instrument),.stage-content>:deep(.percussion-grid-shell){height:724px}.cue{position:absolute;z-index:40;left:50%;top:50%;transform:translate(-50%,-50%);padding:18px 28px;border-radius:18px;color:#20160f;background:#efc98e;box-shadow:0 20px 60px #000b;font-weight:900}.cue--go{top:11%;color:#edf7e9;background:#2f6a51}.activity-shell footer{display:flex;align-items:center;gap:8px;margin-top:12px}.activity-shell footer button{padding:10px 14px;border:0;border-radius:10px;color:#241811;background:#e6bd80}.activity-shell footer small{margin-left:auto;color:#9f9686}</style>
